// Code generated by abstraction-idl from livevoice/probe.thrift. DO NOT EDIT.

package livevoice

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

// ServiceErrorCode is an open vocabulary: a reader keeps a word it has never heard, so
// a value may be none of the constants below. ServiceErrorCode(word) and string(v)
// convert between the raw word and the vocabulary.
type ServiceErrorCode string

const (
	ServiceErrorCodeHandlerError   ServiceErrorCode = "handler_error"
	ServiceErrorCodeInvalidResult  ServiceErrorCode = "invalid_result"
	ServiceErrorCodeUnknownVersion ServiceErrorCode = "unknown_version"
	ServiceErrorCodeUnknownService ServiceErrorCode = "unknown_service"
	ServiceErrorCodeUnknownMethod  ServiceErrorCode = "unknown_method"
	ServiceErrorCodeWrongMode      ServiceErrorCode = "wrong_mode"
)

// ServiceErrorCodeValues returns every member of ServiceErrorCode in declaration order, in a new slice.
func ServiceErrorCodeValues() []ServiceErrorCode {
	return []ServiceErrorCode{ServiceErrorCodeHandlerError, ServiceErrorCodeInvalidResult, ServiceErrorCodeUnknownVersion, ServiceErrorCodeUnknownService, ServiceErrorCodeUnknownMethod, ServiceErrorCodeWrongMode}
}

// Known reports whether v is a member of ServiceErrorCode.
func (v ServiceErrorCode) Known() bool {
	switch v {
	case ServiceErrorCodeHandlerError, ServiceErrorCodeInvalidResult, ServiceErrorCodeUnknownVersion, ServiceErrorCodeUnknownService, ServiceErrorCodeUnknownMethod, ServiceErrorCodeWrongMode:
		return true
	}
	return false
}

// Measurement-only 200 ms audio frame; not a public inference profile.
type Frame struct {
	Sequence int64
	Audio    []byte
}

// Measured backend or long-poll wait to subtract from the local exchange round
// trip.
type Sample struct {
	Sequence int64
	Audio    []byte
	WaitNs   int64
}

type oaVoiceProbeAppendArguments struct {
	Frame Frame
}

type oaVoiceProbeObserveArguments struct {
	Sequence int64
}

type oaServiceFrame struct {
	Version   int32
	Service   string
	Method    string
	Arguments Raw
}

type oaServiceReply struct {
	Version int32
	Service string
	Method  string
	Ok      bool
	Payload Raw
}

type oaServiceError struct {
	Code    string
	Message string
}

type oaVoiceProbeAppendResult struct {
	Value Sample
}

type oaVoiceProbeObserveResult struct {
	Value Sample
}

func encFrame(out []byte, v *Frame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "sequence")
	out = append(out, ':', ' ')
	out = num(out, v.Sequence)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "audio")
	out = append(out, ':', ' ')
	out = esc(out, encodeBinary(v.Audio))
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encSample(out []byte, v *Sample, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "sequence")
	out = append(out, ':', ' ')
	out = num(out, v.Sequence)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "audio")
	out = append(out, ':', ' ')
	out = esc(out, encodeBinary(v.Audio))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "wait_ns")
	out = append(out, ':', ' ')
	out = num(out, v.WaitNs)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAVoiceProbeAppendArguments(out []byte, v *oaVoiceProbeAppendArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "frame")
	out = append(out, ':', ' ')
	out = encFrame(out, &v.Frame, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAVoiceProbeObserveArguments(out []byte, v *oaVoiceProbeObserveArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "sequence")
	out = append(out, ':', ' ')
	out = num(out, v.Sequence)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceFrame(out []byte, v *oaServiceFrame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "arguments")
	out = append(out, ':', ' ')
	out = append(out, v.Arguments...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceReply(out []byte, v *oaServiceReply, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "ok")
	out = append(out, ':', ' ')
	if v.Ok {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "payload")
	out = append(out, ':', ' ')
	out = append(out, v.Payload...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceError(out []byte, v *oaServiceError, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "message")
	out = append(out, ':', ' ')
	out = esc(out, v.Message)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAVoiceProbeAppendResult(out []byte, v *oaVoiceProbeAppendResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encSample(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAVoiceProbeObserveResult(out []byte, v *oaVoiceProbeObserveResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encSample(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *Frame) []byte {
	return append(encFrame(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) decodeFrame() (*Frame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Frame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "sequence":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Sequence = x
			case "audio":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.binary()
				if err != nil {
					return nil, err
				}
				v.Audio = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeSample() (*Sample, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Sample{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "sequence":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Sequence = x
			case "audio":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.binary()
				if err != nil {
					return nil, err
				}
				v.Audio = x
			case "wait_ns":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.WaitNs = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&7 != 7 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAVoiceProbeAppendArguments() (*oaVoiceProbeAppendArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaVoiceProbeAppendArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "frame":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeFrame()
				if err != nil {
					return nil, err
				}
				v.Frame = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAVoiceProbeObserveArguments() (*oaVoiceProbeObserveArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaVoiceProbeObserveArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "sequence":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Sequence = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceFrame() (*oaServiceFrame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceFrame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "arguments":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Arguments = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceReply() (*oaServiceReply, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceReply{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "ok":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Ok = x
			case "payload":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Payload = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceError() (*oaServiceError, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaServiceError{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "message":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Message = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAVoiceProbeAppendResult() (*oaVoiceProbeAppendResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaVoiceProbeAppendResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeSample()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAVoiceProbeObserveResult() (*oaVoiceProbeObserveResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &oaVoiceProbeObserveResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeSample()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func Decode(in []byte) (*Frame, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// refusals is in the order two of them are chosen between.

var refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "trailing_bytes"}

func refusalRank(word string) int {
	for i, w := range refusals {
		if w == word {
			return i
		}
	}
	return -1
}

func encodeBinary(value []byte) string {
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	out := make([]byte, 0, ((len(value)+2)/3)*4)
	for i := 0; i < len(value); i += 3 {
		n := len(value) - i
		v := uint32(value[i]) << 16
		if n > 1 {
			v |= uint32(value[i+1]) << 8
		}
		if n > 2 {
			v |= uint32(value[i+2])
		}
		out = append(out, alphabet[v>>18], alphabet[(v>>12)&63])
		if n > 1 {
			out = append(out, alphabet[(v>>6)&63])
		} else {
			out = append(out, '=')
		}
		if n > 2 {
			out = append(out, alphabet[v&63])
		} else {
			out = append(out, '=')
		}
	}
	return string(out)
}
func (r *reader) binary() ([]byte, error) {
	text, err := r.str()
	if err != nil {
		return nil, err
	}
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	if len(text)%4 != 0 {
		return nil, r.refuse("bad_binary")
	}
	out := make([]byte, 0, len(text)/4*3)
	for i := 0; i < len(text); i += 4 {
		var v uint32
		pad := 0
		for j := 0; j < 4; j++ {
			c := text[i+j]
			digit := -1
			if c == '=' {
				if j < 2 || i+4 != len(text) {
					return nil, r.refuse("bad_binary")
				}
				pad++
				digit = 0
			} else {
				if pad != 0 {
					return nil, r.refuse("bad_binary")
				}
				for k := 0; k < len(alphabet); k++ {
					if alphabet[k] == c {
						digit = k
						break
					}
				}
			}
			if digit < 0 {
				return nil, r.refuse("bad_binary")
			}
			v = (v << 6) | uint32(digit)
		}
		out = append(out, byte(v>>16))
		if pad < 2 {
			out = append(out, byte(v>>8))
		}
		if pad == 0 {
			out = append(out, byte(v))
		}
	}
	if encodeBinary(out) != text {
		return nil, r.refuse("bad_binary")
	}
	return out, nil
}

// A transport consumes or copies frames before returning. WriteFrame is one-way.
type FrameWriter interface{ WriteFrame(frame []byte) error }
type DispatchError string

func (e DispatchError) Error() string { return string(e) }
func servicePayload(frame []byte) (*oaServiceFrame, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return nil, DispatchError("unknown_version")
	}
	return v, nil
}

// ExchangeFrame returns the response associated with this call. Correlation,
// serialization and deadlines belong to the transport, not this codec.
type FrameExchanger interface {
	ExchangeFrame(frame []byte) ([]byte, error)
}

// ServiceError is a reply on the error channel. Code is a ServiceErrorCode
// constant or a word this package has never heard.
type ServiceError struct {
	Code    ServiceErrorCode
	Message string
}

func (e *ServiceError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return string(e.Code)
}
func serviceResponse(frame []byte, service, method string) (Raw, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceReply()
	if err != nil {
		return "", err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return "", r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return "", DispatchError("unknown_version")
	}
	if v.Service != service || v.Method != method {
		return "", DispatchError("mismatched_response")
	}
	if !v.Ok {
		r = &reader{buf: []byte(v.Payload), depth: 1}
		r.ws()
		e, err := r.decodeOAServiceError()
		if err != nil {
			return "", err
		}
		r.ws()
		if r.pos != len(r.buf) {
			return "", r.refuse("trailing_bytes")
		}
		if e.Code == "" {
			return "", DispatchError("invalid_error")
		}
		return "", &ServiceError{Code: ServiceErrorCode(e.Code), Message: e.Message}
	}
	return v.Payload, nil
}
func serviceReply(v *oaServiceFrame, payload Raw, err error) (frame []byte, outErr error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				frame = nil
				outErr = e
			} else {
				panic(p)
			}
		}
	}()
	reply := oaServiceReply{Version: 1, Service: v.Service, Method: v.Method, Ok: err == nil, Payload: payload}
	if err != nil {
		e := oaServiceError{Code: string(ServiceErrorCodeHandlerError), Message: "handler failed"}
		switch x := err.(type) {
		case *ServiceError:
			if x.Code != "" {
				e.Code = string(x.Code)
			}
			e.Message = x.Message
		case DispatchError:
			e.Code = string(x)
			e.Message = ""
		case *Refusal:
			e.Code = x.Word
			e.Message = ""
		}
		reply.Payload = Raw(encOAServiceError(nil, &e, 1))
	}
	frame = encOAServiceReply(nil, &reply, 0)
	// Validate even error diagnostics before making them visible on the wire.
	r := &reader{buf: frame}
	r.ws()
	if _, e := r.decodeOAServiceReply(); e != nil {
		return nil, e
	}
	return frame, nil
}

// EndpointContract is abstraction.facade/endpoint@1, which every dispatcher
// answers beside its own service.
const EndpointContract = "abstraction.facade/endpoint@1"

// DescribedService is a dispatcher of any generated package, as
// abstraction.facade/endpoint@1 Describe lists it.
type DescribedService interface {
	DescribeService() (contract string, ready bool, why string)
}

// DescribeEndpoint answers an abstraction.facade/endpoint@1 Describe frame for
// an endpoint hosting services, in that order. program and version are the
// provider's own display name and version, never authority. A frame for another
// service reads unknown_service.
func DescribeEndpoint(frame []byte, program, version string, services ...DescribedService) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != EndpointContract {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	if v.Method != "Describe" {
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
	r := &reader{buf: []byte(v.Arguments)}
	r.ws()
	empty := false
	if r.pos < len(r.buf) && r.buf[r.pos] == '{' {
		r.pos++
		r.ws()
		if r.pos < len(r.buf) && r.buf[r.pos] == '}' {
			r.pos++
			r.ws()
			empty = r.pos == len(r.buf)
		}
	}
	if !empty {
		return serviceReply(v, "", &Refusal{Word: "unknown_field"})
	}
	out := append([]byte(nil), "{\"value\":{\"outcome\":\"described\",\"program\":"...)
	out = esc(out, program)
	out = append(out, ",\"version\":"...)
	out = esc(out, version)
	out = append(out, ",\"services\":["...)
	for i, service := range services {
		contract, ready, why := service.DescribeService()
		readiness := "ready"
		if !ready {
			readiness = "not_ready"
		}
		if i > 0 {
			out = append(out, ',')
		}
		out = append(out, "{\"contract\":"...)
		out = esc(out, contract)
		out = append(out, ",\"readiness\":\""+readiness+"\",\"why\":"...)
		out = esc(out, why)
		out = append(out, ",\"guarantees\":[],\"capabilities\":{}}"...)
	}
	return serviceReply(v, Raw(append(out, "]}}"...)), nil)
}

// ServedService is a dispatcher of any generated package that ServeEndpoint
// routes frames to by its wire name.
type ServedService interface {
	DescribedService
	ServiceContract() string
}

// ServeEndpoint answers one request-response frame for an endpoint hosting
// services. A Describe frame lists all of them in the order given; any other
// frame goes to the service it names. A service that takes only one-way frames
// reads wrong_mode, and a frame naming none of them reads unknown_service.
func ServeEndpoint(frame []byte, program, version string, services ...ServedService) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service == EndpointContract {
		described := make([]DescribedService, len(services))
		for i, service := range services {
			described[i] = service
		}
		return DescribeEndpoint(frame, program, version, described...)
	}
	for _, service := range services {
		if service.ServiceContract() != v.Service {
			continue
		}
		if exchanger, ok := service.(interface{ ExchangeFrame([]byte) ([]byte, error) }); ok {
			return exchanger.ExchangeFrame(frame)
		}
		return serviceReply(v, "", DispatchError("wrong_mode"))
	}
	return serviceReply(v, "", DispatchError("unknown_service"))
}

type VoiceProbe interface {
	Append(frame_ Frame) (Sample, error)
	Observe(sequence int64) (Sample, error)
}
type VoiceProbeTransport interface {
	FrameExchanger
}
type VoiceProbeClient struct{ transport VoiceProbeTransport }

func NewVoiceProbeClient(t VoiceProbeTransport) *VoiceProbeClient {
	return &VoiceProbeClient{transport: t}
}

type VoiceProbeDispatcher struct{ Handler VoiceProbe }

func (c *VoiceProbeClient) Append(frame_ Frame) (result Sample, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := oaVoiceProbeAppendArguments{Frame: frame_}
	v := oaServiceFrame{Version: 1, Service: "oa.test/livevoice-probe@1", Method: "Append", Arguments: Raw(encOAVoiceProbeAppendArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *oaVoiceProbeAppendResult
	decoded, err = r.decodeOAVoiceProbeAppendResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *VoiceProbeClient) Observe(sequence int64) (result Sample, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := oaVoiceProbeObserveArguments{Sequence: sequence}
	v := oaServiceFrame{Version: 1, Service: "oa.test/livevoice-probe@1", Method: "Observe", Arguments: Raw(encOAVoiceProbeObserveArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *oaVoiceProbeObserveResult
	decoded, err = r.decodeOAVoiceProbeObserveResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}

// DescribeService is this dispatcher's service as abstraction.facade/endpoint@1 Describe lists it:
// ready unless its handler implements Ready() (bool, string) and reports otherwise.
func (d *VoiceProbeDispatcher) DescribeService() (contract string, ready bool, why string) {
	if h, ok := d.Handler.(interface{ Ready() (bool, string) }); ok {
		if ready, why = h.Ready(); ready {
			why = ""
		}
		return "oa.test/livevoice-probe@1", ready, why
	}
	return "oa.test/livevoice-probe@1", true, ""
}

// ServiceContract is the wire name ServeEndpoint routes this dispatcher's frames by.
func (d *VoiceProbeDispatcher) ServiceContract() string { return "oa.test/livevoice-probe@1" }
func (d *VoiceProbeDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "oa.test/livevoice-probe@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "Append":
		return DispatchError("wrong_mode")
	case "Observe":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *VoiceProbeDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service == EndpointContract {
		return DescribeEndpoint(frame, "", "", d)
	}
	if v.Service != "oa.test/livevoice-probe@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "Append":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAVoiceProbeAppendArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeAppend(args)
		return serviceReply(v, payload, err)
	case "Observe":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAVoiceProbeObserveArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeObserve(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *VoiceProbeDispatcher) invokeAppend(args *oaVoiceProbeAppendArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
			} else {
				err = &ServiceError{Code: ServiceErrorCodeHandlerError, Message: "handler failed"}
			}
		}
	}()
	var result Sample
	result, err = d.Handler.Append(args.Frame)
	if err != nil {
		return
	}
	value := oaVoiceProbeAppendResult{Value: result}
	payload = Raw(encOAVoiceProbeAppendResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAVoiceProbeAppendResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
	}
	return
}
func (d *VoiceProbeDispatcher) invokeObserve(args *oaVoiceProbeObserveArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
			} else {
				err = &ServiceError{Code: ServiceErrorCodeHandlerError, Message: "handler failed"}
			}
		}
	}()
	var result Sample
	result, err = d.Handler.Observe(args.Sequence)
	if err != nil {
		return
	}
	value := oaVoiceProbeObserveResult{Value: result}
	payload = Raw(encOAVoiceProbeObserveResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAVoiceProbeObserveResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: ServiceErrorCodeInvalidResult}
	}
	return
}
