# Code generated by abstraction-idl from livevoice/probe.thrift. DO NOT EDIT.

"""oa.test.livevoice: generated contract types, vocabularies and service clients."""

from ._codec import (
    DispatchError,
    Frame,
    Refusal,
    Sample,
    ServiceError,
    ServiceErrorCode,
    VoiceProbe,
    VoiceProbeClient,
    decode,
    encode,
)

__all__ = [
    "DispatchError",
    "Frame",
    "Refusal",
    "Sample",
    "ServiceError",
    "ServiceErrorCode",
    "VoiceProbe",
    "VoiceProbeClient",
    "decode",
    "encode",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
