# Code generated by abstraction-idl from livevoice/probe.thrift. DO NOT EDIT.

from __future__ import annotations

import dataclasses
import enum

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def _esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def _num(out, n):
    out += str(int(n)).encode("ascii")


def _pad(out, depth):
    out += b" " * (depth * 2)


def _strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        _pad(out, depth + 1)
        _esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


def _raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                _pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            _pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            _pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def _rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"

def _esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        _esc_byte(out, c)
    out += b'"'


try:
    from enum import StrEnum as _StrEnum
except ImportError:  # Python 3.10
    class _StrEnum(str, enum.Enum):
        def __str__(self):
            return self.value


def _closed_enum(cls, value):
    if value is not None and not isinstance(value, str):
        raise Refusal("wrong_type", 0)
    try:
        cls(value)
    except ValueError:
        raise Refusal("bad_enum", 0) from None


def _open_enum(cls, value):
    try:
        return cls(value)
    except ValueError:
        return value


class ServiceErrorCode(_StrEnum):
    HANDLER_ERROR = "handler_error"
    INVALID_RESULT = "invalid_result"
    UNKNOWN_VERSION = "unknown_version"
    UNKNOWN_SERVICE = "unknown_service"
    UNKNOWN_METHOD = "unknown_method"
    WRONG_MODE = "wrong_mode"


@dataclasses.dataclass(kw_only=True)
class Frame:
    """Measurement-only 200 ms audio frame; not a public inference profile."""

    sequence: int = 0
    audio: bytes = b""


@dataclasses.dataclass(kw_only=True)
class Sample:
    """Measured backend or long-poll wait to subtract from the local exchange round
    trip."""

    sequence: int = 0
    audio: bytes = b""
    wait_ns: int = 0


@dataclasses.dataclass(kw_only=True)
class _VoiceProbeAppendArguments:
    frame: Frame = dataclasses.field(default_factory=Frame)


@dataclasses.dataclass(kw_only=True)
class _VoiceProbeObserveArguments:
    sequence: int = 0


@dataclasses.dataclass(kw_only=True)
class _ServiceFrame:
    version: int = 0
    service: str = ""
    method: str = ""
    arguments: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceReply:
    version: int = 0
    service: str = ""
    method: str = ""
    ok: bool = False
    payload: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceError:
    code: str = ""
    message: str = ""


@dataclasses.dataclass(kw_only=True)
class _VoiceProbeAppendResult:
    value: Sample = dataclasses.field(default_factory=Sample)


@dataclasses.dataclass(kw_only=True)
class _VoiceProbeObserveResult:
    value: Sample = dataclasses.field(default_factory=Sample)


def _write_frame(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "sequence")
    out += b": "
    _num(out, v.sequence)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "audio")
    out += b": "
    _esc(out, _encode_binary(v.audio))
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_sample(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "sequence")
    out += b": "
    _num(out, v.sequence)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "audio")
    out += b": "
    _esc(out, _encode_binary(v.audio))
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "wait_ns")
    out += b": "
    _num(out, v.wait_ns)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_voice_probe_append_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "frame")
    out += b": "
    _write_frame(out, v.frame, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_voice_probe_observe_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "sequence")
    out += b": "
    _num(out, v.sequence)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_frame(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_reply(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_error(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "code")
    out += b": "
    _esc(out, v.code)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "message")
    out += b": "
    _esc(out, v.message)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_voice_probe_append_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_sample(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_voice_probe_observe_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_sample(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    _write_frame(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    """Bytes the contract refuses: word names the rule, offset the byte."""

    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1


def _read_frame(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Frame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "sequence":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.sequence = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "audio":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.audio = _decode_binary(r.string())
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_sample(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Sample()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "sequence":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.sequence = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "audio":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.audio = _decode_binary(r.string())
            elif key == "wait_ns":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.wait_ns = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _read_oa_voice_probe_append_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _VoiceProbeAppendArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "frame":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.frame = _read_frame(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_voice_probe_observe_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _VoiceProbeObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "sequence":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.sequence = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_frame(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_reply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_error(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_voice_probe_append_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _VoiceProbeAppendResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_sample(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_voice_probe_observe_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _VoiceProbeObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_sample(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _read_frame(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# _REFUSALS is in the order two of them are chosen between.

_REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_binary", "trailing_bytes"]


def _refusal_rank(word):
    return _REFUSALS.index(word) if word in _REFUSALS else -1

def _encode_binary(value):
    if type(value) is not bytes:
        raise Refusal("wrong_type", 0)
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    out = []
    for i in range(0, len(value), 3):
        chunk = value[i:i+3]
        v = int.from_bytes(chunk, "big") << (8 * (3-len(chunk)))
        out.extend((alphabet[v >> 18], alphabet[(v >> 12) & 63], alphabet[(v >> 6) & 63] if len(chunk)>1 else "=", alphabet[v & 63] if len(chunk)>2 else "="))
    return "".join(out)

def _decode_binary(text):
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    def bad():
        raise _Reader(b"").refuse("bad_binary")
    if len(text) % 4: bad()
    out = bytearray()
    for i in range(0,len(text),4):
        v, pad = 0, 0
        for j,c in enumerate(text[i:i+4]):
            if c == "=":
                if j<2 or i+4 != len(text): bad()
                pad += 1
                digit = 0
            else:
                if pad: bad()
                digit = alphabet.find(c)
                if digit < 0: bad()
            v = (v << 6) | digit
        out.append(v >> 16)
        if pad < 2: out.append((v >> 8) & 255)
        if pad == 0: out.append(v & 255)
    result = bytes(out)
    if _encode_binary(result) != text: bad()
    return result


class DispatchError(ValueError):
    """A frame that names no version, service or method this module speaks."""

    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = _ServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(_write_oa_service_frame, v, 0)
    _service_decode(_read_oa_service_frame, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "binary":
        valid = type(value) is bytes
    elif kind == "string":
        valid = type(value) is str
    elif kind == "enum":
        valid = value is None or isinstance(value, str)
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)


class ServiceError(Exception):
    """The service answered the call with an error code and message."""

    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_read_oa_service_reply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_read_oa_service_error, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "Frame": (Frame, [("sequence", "i64", "never"), ("audio", "binary", "never"), ]),
    "Sample": (Sample, [("sequence", "i64", "never"), ("audio", "binary", "never"), ("wait_ns", "i64", "never"), ]),
    "OAVoiceProbeAppendArguments": (_VoiceProbeAppendArguments, [("frame", "Frame", "never"), ]),
    "OAVoiceProbeObserveArguments": (_VoiceProbeObserveArguments, [("sequence", "i64", "never"), ]),
    "OAServiceFrame": (_ServiceFrame, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("arguments", "json", "never"), ]),
    "OAServiceReply": (_ServiceReply, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("ok", "bool", "never"), ("payload", "json", "never"), ]),
    "OAServiceError": (_ServiceError, [("code", "string", "never"), ("message", "string", "never"), ]),
    "OAVoiceProbeAppendResult": (_VoiceProbeAppendResult, [("value", "Sample", "never"), ]),
    "OAVoiceProbeObserveResult": (_VoiceProbeObserveResult, [("value", "Sample", "never"), ]),
}


class VoiceProbe:
    """Isolated latency instrument using generated codecs and the production
    identity-bound transport."""

    def append(self, frame: Frame) -> Sample:
        raise NotImplementedError

    def observe(self, sequence: int) -> Sample:
        raise NotImplementedError


class VoiceProbeClient(VoiceProbe):
    """Calls oa.test/livevoice-probe@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def append(self, frame: Frame) -> Sample:
        _service_check("Frame", frame)
        _args = _VoiceProbeAppendArguments()
        _args.frame = frame
        _arguments = _service_encode(_write_oa_voice_probe_append_arguments, _args, 1)
        _service_decode(_read_oa_voice_probe_append_arguments, _arguments, 1)
        _request = _service_request("oa.test/livevoice-probe@1", "Append", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "oa.test/livevoice-probe@1", "Append")
        _result = _service_decode(_read_oa_voice_probe_append_result, _payload, 1)
        return _result.value

    def observe(self, sequence: int) -> Sample:
        _service_check("i64", sequence)
        _args = _VoiceProbeObserveArguments()
        _args.sequence = sequence
        _arguments = _service_encode(_write_oa_voice_probe_observe_arguments, _args, 1)
        _service_decode(_read_oa_voice_probe_observe_arguments, _arguments, 1)
        _request = _service_request("oa.test/livevoice-probe@1", "Observe", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "oa.test/livevoice-probe@1", "Observe")
        _result = _service_decode(_read_oa_voice_probe_observe_result, _payload, 1)
        return _result.value
