[package]
name="credentials-consumer"
version="0.0.0"
edition="2021"
[dependencies]
abstraction-facade-native={path="../../../../openabstractions-flat/abstraction-facade/rust-native"}
abstraction-facade-credentials={path="../../../../openabstractions-flat/abstraction-facade/rust-credentials"}
[[bin]]
name="credentials-consumer"
path="main.rs"
