package main

const credentialsPage = `<!doctype html><meta charset="utf-8"><title>OpenAbstractions credentials</title>
<style>body{font:16px system-ui;max-width:960px;margin:2rem auto;padding:1rem}input,select,textarea,button{font:inherit;margin:.3rem;padding:.4rem}button{cursor:pointer}section{border-top:1px solid #aaa;padding:1rem 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}.record{border-left:6px solid #ccc;padding:.2rem .6rem;margin:.4rem 0}.error{color:#b22}</style>
<h1>Credentials</h1>
<p>Names, kinds, states, revisions, targets, consumers and applications of secrets registered in this account. The secret itself is typed once, sent once, and is never shown back, logged or echoed here.</p>
<p><a id="back" href="#">Back to service control panel</a></p>
<section><h2>Registered credentials</h2><button id="list-start">List credentials</button><button id="list-next" disabled>Next page</button><pre id="list-status"></pre><pre id="limits"></pre><div id="records"></div></section>
<section><h2>Add a credential</h2><p>Registers a new name with an empty expected revision; a name already in use conflicts.</p>
<form id="add-form"><input id="add-name" required placeholder="name"><select id="add-kind" aria-label="Kind"><option value="bearer">bearer</option><option value="header">header</option></select><input id="add-header" placeholder="header name (kind: header)"><input id="add-targets" required placeholder="targets, comma-separated"><input id="add-consumers" required placeholder="consumers, comma-separated"><input id="add-expires" type="datetime-local" aria-label="Expiry (optional)"><input id="add-secret" type="password" autocomplete="off" required placeholder="secret"><button>Add</button></form>
<pre id="add-status"></pre></section>
<section><h2>Rotate</h2><p>Replaces the bytes and expiry of an existing name at the revision a listing showed.</p>
<form id="rotate-form"><input id="rotate-name" required placeholder="name"><input id="rotate-revision" required placeholder="expected revision (from listing)"><input id="rotate-expires" type="datetime-local" aria-label="Expiry (optional)"><input id="rotate-secret" type="password" autocomplete="off" required placeholder="new secret"><button>Rotate</button></form>
<pre id="rotate-status"></pre></section>
<section><h2>Revoke</h2><p>Destroys the bytes at once and keeps a tombstone, at the revision a listing showed.</p>
<form id="revoke-form"><input id="revoke-name" required placeholder="name"><input id="revoke-revision" required placeholder="expected revision (from listing)"><button>Revoke</button></form>
<pre id="revoke-status"></pre></section>
<section><h2>Allow or deny a program</h2><p>Writes the exact rule abstraction.credentials/apply on credential:&lt;name&gt; for one account and absolute program path, at the currently listed rights policy revision. This calls the same rights operator as the service control panel's Rights section.</p>
<button id="allow-list">List rights policy</button><pre id="allow-status"></pre>
<form id="allow-form"><input id="allow-name" required placeholder="credential name"><input id="allow-account" required placeholder="account"><input id="allow-program" required placeholder="absolute program path"><select id="allow-permit" aria-label="Rule"><option value="permit">allow</option><option value="deny">deny</option></select><button>Set at listed revision</button></form></section>
<script>
const key=new URLSearchParams(location.search).get('k');
const el=id=>document.getElementById(id);
function show(id,x){el(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function call(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Panel-Key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
el('back').href='/?k='+encodeURIComponent(key);
function commaList(v){return v.split(',').map(x=>x.trim()).filter(x=>x)}
function isoOrEmpty(v){if(!v)return '';const d=new Date(v);return isNaN(d.getTime())?'':d.toISOString()}
const outcomeText={forbidden:'This panel is not authorized for credentials; nothing changed.',unavailable:'The credentials service could not complete this; list again before another conditional edit.',gap:'The listing changed; start again.',invalid:'The credentials service rejected this as invalid.',no_secure_store:'This runtime has no configured platform store; nothing was stored.',exhausted:'This account already holds its maximum number of credentials.',unsupported_kind:'This runtime\'s applier does not support that kind.',unknown:'No credential has that name.',conflict:'The listed revision is stale; list again before retrying.'};
function outcomeStatus(o){return outcomeText[o]||'Credentials service outcome: '+o}
function scopeText(s){return 'targets: '+s.Targets.join(', ')+'; consumers: '+s.Consumers.join(', ')}
function metaBox(m){const box=document.createElement('div');box.className='record';const t=document.createElement('pre');t.textContent=m.Name+'  ['+m.Kind+(m.Header?'/'+m.Header:'')+']  '+m.State+'\nrevision '+m.Revision+'\n'+scopeText(m.Scope)+(m.Expires?'\nexpires '+m.Expires:'')+(m.LastApplied?'\nlast applied '+m.LastApplied:'\nnever applied')+'\nregistered by '+m.RegisteredBy.Program+' at '+m.Registered;box.append(t);if(m.State!=='revoked'){const rot=document.createElement('button');rot.textContent='Use for rotate';rot.onclick=()=>{el('rotate-name').value=m.Name;el('rotate-revision').value=m.Revision};const rev=document.createElement('button');rev.textContent='Use for revoke';rev.onclick=()=>{el('revoke-name').value=m.Name;el('revoke-revision').value=m.Revision};const allow=document.createElement('button');allow.textContent='Allow/deny this name';allow.onclick=()=>{el('allow-name').value=m.Name};box.append(rot,rev,allow)}return box}
let listCursor='';
async function list(){try{const p=await call('/credentials?cursor='+encodeURIComponent(listCursor));if(p.Outcome!=='page'){show('list-status',outcomeStatus(p.Outcome));el('list-next').disabled=true;return}listCursor=p.Next;el('list-next').disabled=p.Complete;show('limits','store: '+p.Limits.SecureStore+'; kinds: '+p.Limits.SupportedKinds.join(', ')+'; max secret bytes: '+p.Limits.MaxSecretBytes+'; max credentials: '+p.Limits.MaxCredentials);show('list-status',p.Records.length?(p.Complete?'End of list.':'More records remain.'):'No credentials registered.');el('records').replaceChildren();for(const m of p.Records)el('records').append(metaBox(m))}catch(e){show('list-status',e.message)}}
el('list-start').onclick=()=>{listCursor='';return list()};el('list-next').onclick=list;
el('add-form').onsubmit=async e=>{e.preventDefault();const secret=el('add-secret').value;el('add-secret').value='';const body={action:'add',name:el('add-name').value,kind:el('add-kind').value,header:el('add-header').value,targets:commaList(el('add-targets').value),consumers:commaList(el('add-consumers').value),expires:isoOrEmpty(el('add-expires').value),secret,expected_revision:''};try{const r=await call('/credentials',body);show('add-status',r.Outcome==='stored'?'Stored '+body.name+' at revision '+r.Revision+'. List again to see it.':outcomeStatus(r.Outcome));if(r.Outcome==='stored')el('add-form').reset()}catch(err){show('add-status',err.message)}};
el('rotate-form').onsubmit=async e=>{e.preventDefault();const secret=el('rotate-secret').value;el('rotate-secret').value='';const name=el('rotate-name').value;const body={action:'rotate',name,expected_revision:el('rotate-revision').value,expires:isoOrEmpty(el('rotate-expires').value),secret};try{const r=await call('/credentials',body);show('rotate-status',r.Outcome==='rotated'?'Rotated '+name+' to revision '+r.Revision+'. List again before another conditional edit.':outcomeStatus(r.Outcome))}catch(err){show('rotate-status',err.message)}};
el('revoke-form').onsubmit=async e=>{e.preventDefault();const name=el('revoke-name').value;const body={action:'revoke',name,expected_revision:el('revoke-revision').value};try{const r=await call('/credentials',body);show('revoke-status',r.Outcome==='revoked'?'Revoked '+name+' at revision '+r.Revision+'.':outcomeStatus(r.Outcome))}catch(err){show('revoke-status',err.message)}};
let allowRevision='';
const rightsOutcomeText={forbidden:'This panel is not authorized to administer rights; nothing was changed.',unavailable:'The rights service could not complete this; list again before another edit.',gap:'The policy changed while listing; start again.',invalid:'The rights service rejected this rule as invalid.',conflict:'The policy changed since it was listed; list again before another edit.'};
function rightsOutcomeStatus(o){return rightsOutcomeText[o]||'Rights service outcome: '+o}
el('allow-list').onclick=async()=>{try{const p=await call('/rights?cursor=');if(p.Outcome!=='page'){allowRevision='';show('allow-status',rightsOutcomeStatus(p.Outcome));return}allowRevision=p.Revision;show('allow-status','Policy revision '+p.Revision+'. Choose allow or deny below.')}catch(e){allowRevision='';show('allow-status',e.message)}};
el('allow-form').onsubmit=async e=>{e.preventDefault();if(!allowRevision){show('allow-status','List rights policy before allowing.');return}const name=el('allow-name').value,program=el('allow-program').value,used=allowRevision,permit=el('allow-permit').value==='permit';const body={edit:'set',revision:allowRevision,account:el('allow-account').value,program,action:'abstraction.credentials/apply',resource:'credential:'+name,permit};try{const r=await call('/rights',body);allowRevision='';show('allow-status',r.Outcome==='applied'?(permit?'Allowed ':'Denied ')+program+' to apply '+name+' at revision '+used+'. List rights policy again before another edit.':rightsOutcomeStatus(r.Outcome))}catch(err){allowRevision='';show('allow-status',err.message)}};
</script>`
