package main

// inferencePage is the Panel's inference page: hosts with each credential's
// spend today, the gateway window's local keys, and the inference audit. It
// renders every value as text and calls only /inference/* with the panel key.
const inferencePage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Inference</title>
<style>body{font:16px system-ui;max-width:1100px;margin:2rem auto;padding:1rem}input,select,button{font:inherit;margin:.3rem;padding:.4rem}section{border-top:1px solid #aaa;padding:1rem 0}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #ddd;padding:.3rem;text-align:left;vertical-align:top;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere}.key{font-family:monospace;background:#fff4e5;border-left:6px solid #b60;padding:.4rem .6rem}</style></head><body>
<h1>Inference</h1><p>Model calls the runtime performs: its hosts, the local keys of the gateway window, and every decision it recorded. Each call below is decided by the runtime for this Panel: host.manage, key.issue or audit.read.</p>
<section><h2>Hosts and spend</h2><button id="hosts-list">List hosts</button><pre id="hosts-status"></pre><table><thead><tr><th>Name</th><th>Class</th><th>Kind</th><th>Base</th><th>Credential</th><th>Profiles</th><th>Declared by</th><th>State</th><th>Spend today</th><th>Ceiling</th><th></th></tr></thead><tbody id="hosts"></tbody></table>
<form id="host-add"><input id="host-name" required placeholder="name (a local kind: ollama, lmstudio, lemonade)"><input id="host-base" required placeholder="base URL"><input id="host-wire" placeholder="wire, for a hosted host (openai-compatible, anthropic-messages)"><input id="host-credential" placeholder="credential name"><input id="host-profiles" placeholder="profiles (default by wire: chat, embed, transcription, speech, image)"><input id="host-tokens" type="number" min="0" placeholder="tokens per day"><input id="host-micros" type="number" min="0" placeholder="spend per day, currency millionths"><button>Add at listed revision</button></form><p>Adding a host also writes the complete rule on it for the command line and this Panel, and for a hosted host the runtime's apply rule on its credential.</p></section>
<section><h2>Gateway window</h2><p>The window lets unchanged programs that speak the OpenAI or Anthropic API reach the runtime at a loopback address with a local key. It is off by default, listens on 127.0.0.1 only, and the setting survives a restart. Changing it is decided as host.manage.</p><button id="gateway-read">Read setting</button><pre id="gateway-status"></pre><form id="gateway-set"><input id="gateway-address" placeholder="127.0.0.1:PORT (default: the recorded address, or 127.0.0.1:8793)"><button id="gateway-on" type="submit">Open at listed revision</button><button id="gateway-off" type="button">Close at listed revision</button></form></section>
<section><h2>Gateway window keys</h2><p>A key lets one program use the window with its base URL. It grants nothing by itself: the program still needs abstraction.inference/complete on a host, and apply on a hosted credential. The key is shown once.</p><button id="keys-list">List keys</button><pre id="keys-status"></pre><table><thead><tr><th>Program</th><th>State</th><th>Credential</th><th>Issued</th><th>Issued by</th><th></th></tr></thead><tbody id="keys"></tbody></table>
<form id="key-issue"><input id="key-program" required placeholder="absolute program path"><input id="key-credential" placeholder="hosted credential (optional)"><button>Issue key</button></form><div id="key-shown"></div></section>
<section><h2>Audit</h2><p>Decisions from native calls and the gateway window, with the rung each caller was bound at.</p><button id="audit-start">Read from the oldest</button><button id="audit-next" disabled>Next page</button><pre id="audit-status"></pre><table><thead><tr><th>#</th><th>Time</th><th>Route</th><th>Rung</th><th>Program</th><th>Host</th><th>Model</th><th>Credential</th><th>Outcome</th><th>Reason</th><th>Tokens in/out</th></tr></thead><tbody id="audit"></tbody></table></section>
<script>
const key=new URLSearchParams(location.search).get('k');let hostsRevision='',gatewayRevision='',auditCursor=0;
const el=id=>document.getElementById(id);function show(id,x){el(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function call(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Panel-Key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
const outcomeText={forbidden:'The runtime did not permit this Panel; nothing was changed.',unavailable:'The runtime could not answer; nothing is assumed. Try again.',conflict:'The configuration changed or the program already holds a key; list again.',invalid:'The runtime refused the request as invalid.',unknown:'Nothing by that name.',no_secure_store:'The runtime has no platform store to hold a key.'};
function outcome(o,reason){return (outcomeText[o]||('Outcome: '+o))+(reason?' ('+reason+')':'')}
function row(tbody,cells,button){const tr=document.createElement('tr');for(const c of cells){const td=document.createElement('td');td.textContent=c==null?'':String(c);tr.append(td)}const td=document.createElement('td');if(button)td.append(button);tr.append(td);el(tbody).append(tr)}
function action(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;return b}
async function hosts(){try{const l=await call('/inference/hosts');el('hosts').replaceChildren();if(l.Outcome!=='page'){hostsRevision='';show('hosts-status',outcome(l.Outcome));return}hostsRevision=l.Revision;show('hosts-status','Configuration revision '+l.Revision+'. '+(l.Hosts.length?'':'No hosts.'));for(const h of l.Hosts){const e=h.Entry;row('hosts',[e.Name,e.Hosted?'hosted':'local',e.Kind,e.Base,e.Credential,(e.Profiles||[]).join(', '),e.DeclaredBy||'',h.Up?'up':'down: '+h.Why,h.Spend?h.Spend.Tokens+' tokens, '+h.Spend.Micros+' micros ('+h.Spend.Day+')':'',e.Ceiling?e.Ceiling.TokensPerDay+' tokens, '+e.Ceiling.MicrosPerDay+' micros':''],action('Remove',()=>hostEdit({edit:'remove',name:e.Name})))}}catch(e){hostsRevision='';show('hosts-status',e.message)}}
async function hostEdit(body){if(!hostsRevision){show('hosts-status','List hosts before changing them.');return}try{const c=await call('/inference/hosts',{...body,revision:hostsRevision});hostsRevision='';show('hosts-status',c.Outcome==='applied'?'Applied; configuration revision '+c.Revision+(c.Reason?'\nNot every rule was written: '+c.Reason:'')+'\nList again before another change.':outcome(c.Outcome,c.Reason))}catch(e){show('hosts-status',e.message)}}
el('hosts-list').onclick=hosts;
el('host-add').onsubmit=ev=>{ev.preventDefault();const wire=el('host-wire').value.trim(),name=el('host-name').value.trim(),tokens=Number(el('host-tokens').value||0),micros=Number(el('host-micros').value||0);const profiles=el('host-profiles').value.split(',').map(s=>s.trim()).filter(Boolean);const host={Name:name,Hosted:!!wire,Kind:wire||name,Base:el('host-base').value.trim(),Credential:el('host-credential').value.trim()};if(profiles.length)host.Profiles=profiles;if(tokens||micros)host.Ceiling={TokensPerDay:tokens,MicrosPerDay:micros};hostEdit({edit:'add',host})};
function gatewayText(s){return 'Setting: '+(s.Open?'on at '+s.Address:'off')+'\nWindow: '+(s.Listening?'listening on http://'+s.ListeningAddress+'/v1 (OpenAI) and http://'+s.ListeningAddress+' (Anthropic)':'closed'+(s.Why?': '+s.Why:''))+'\nSetting revision '+s.Revision+'.'}
async function gateway(){try{const s=await call('/inference/gateway');if(s.Outcome!=='page'){gatewayRevision='';show('gateway-status',outcome(s.Outcome));return}gatewayRevision=s.Revision;show('gateway-status',gatewayText(s))}catch(e){gatewayRevision='';show('gateway-status',e.message)}}
async function gatewaySet(open){if(!gatewayRevision){show('gateway-status','Read the setting before changing it.');return}try{const c=await call('/inference/gateway',{revision:gatewayRevision,open,address:open?el('gateway-address').value.trim():''});gatewayRevision='';if(c.Outcome!=='applied'){show('gateway-status',outcome(c.Outcome,c.Reason));return}await gateway()}catch(e){gatewayRevision='';show('gateway-status',e.message)}}
el('gateway-read').onclick=gateway;el('gateway-set').onsubmit=ev=>{ev.preventDefault();gatewaySet(true)};el('gateway-off').onclick=()=>gatewaySet(false);
function time(ms){return ms?new Date(ms).toISOString():''}
async function keys(){try{const l=await call('/inference/keys');el('keys').replaceChildren();if(l.Outcome!=='page'){show('keys-status',outcome(l.Outcome));return}show('keys-status',l.Keys.length?'':'No keys issued.');for(const k of l.Keys)row('keys',[k.Program,k.State,k.Credential,time(k.IssuedUnixMs),k.IssuedBy],k.State==='active'?action('Revoke',()=>keyEdit({edit:'revoke',program:k.Program})):null)}catch(e){show('keys-status',e.message)}}
async function keyEdit(body){el('key-shown').replaceChildren();try{const r=await call('/inference/keys',body);if(r.Outcome!=='applied'){show('keys-status',outcome(r.Outcome,r.Reason));return}if(body.edit==='issue'){const p=document.createElement('p');p.textContent='Key for '+r.Record.Program+', shown once. Give it to that program as its API key, with the window as its base URL:';const k=document.createElement('div');k.className='key';k.textContent=r.Key;el('key-shown').append(p,k)}show('keys-status',body.edit==='issue'?'Issued. List again to refresh.':'Revoked. The window refuses the key from its next request.')}catch(e){show('keys-status',e.message)}}
el('keys-list').onclick=keys;
el('key-issue').onsubmit=ev=>{ev.preventDefault();keyEdit({edit:'issue',program:el('key-program').value.trim(),credential:el('key-credential').value.trim()})};
async function audit(){try{const p=await call('/inference/audit?cursor='+auditCursor);if(p.Outcome==='gap'){auditCursor=p.Next;show('audit-status','Older entries are no longer retained; reading from '+p.Next+'.');return audit()}if(p.Outcome!=='page'){show('audit-status',outcome(p.Outcome));el('audit-next').disabled=true;return}for(const e of p.Entries)row('audit',[e.Sequence,time(e.UnixMs),e.Route,e.Rung,e.Program,e.Host,e.Model,e.Credential,e.Outcome,e.Reason,e.TokensIn+'/'+e.TokensOut]);auditCursor=p.Next;el('audit-next').disabled=p.AtEnd;show('audit-status',p.AtEnd?'End of the audit; read the next page later for new decisions.':'More entries remain.')}catch(e){show('audit-status',e.message)}}
el('audit-start').onclick=()=>{auditCursor=0;el('audit').replaceChildren();audit()};el('audit-next').onclick=audit;
</script></body></html>`
