package main

const servicePage = `<!doctype html><meta charset="utf-8"><title>OpenAbstractions services</title>
<style>body{font:16px system-ui;max-width:960px;margin:2rem auto;padding:1rem}input,textarea,button{font:inherit;margin:.3rem;padding:.4rem}textarea{width:95%;height:10rem}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{cursor:pointer}section{border-top:1px solid #aaa;padding:1rem 0}.error{color:#b22}</style>
<h1>Service control panel</h1><p>Work accepted for this panel program only. Other applications keep their own scope. Service absence is reported explicitly.</p>
<button id="status">Check runtime</button><pre id="runtime"></pre>
<section><h2>Accepted work</h2><button id="restart">Start inventory</button><button id="next" disabled>Next page</button><p id="inventory-status"></p><div id="records"></div></section>
<section><h2>Submit verified HTTP download</h2><p>Save the recovery record before submitting. An uncertain reply must be reconciled with the same key and owner.</p>
<form id="submit"><input id="url" type="url" required placeholder="HTTP URL"><input id="digest" required placeholder="sha256:…"><input id="size" type="number" min="0" required placeholder="bytes"><input id="requestkey" required placeholder="unique request key"><button>Save recovery record and submit</button></form>
<select id="saved" aria-label="Saved recovery requests"></select><button id="reconcile">Reconcile saved request</button><button id="export">Export saved recovery record</button><pre id="operation"></pre></section>
<section><h2>Questions</h2><p>Answers and retirements record this person's decision. The question service decides whether this panel may act; retiring tells the application the question is gone, which is neither approval nor refusal.</p><button id="questions-start">List questions</button><button id="questions-next" disabled>Next page</button><pre id="questions-status"></pre><div id="questions"></div></section>
<section><h2>Rights</h2><p>Grants and denies are exact rules for one account, program, action and resource. Every edit applies only at the listed policy revision; the rights service decides whether this panel may administer policy. Resource services still check each call.</p><button id="rights-start">List policy</button><button id="rights-next" disabled>Next page</button><pre id="rights-status"></pre><div id="rights"></div>
<form id="rights-grant"><input id="rights-account" required placeholder="account"><input id="rights-program" required placeholder="absolute program path"><select id="rights-action" aria-label="Catalogue action"></select><input id="rights-resource" required placeholder="resource"><select id="rights-permit" aria-label="Rule"><option value="permit">permit</option><option value="deny">deny</option></select><button>Set at listed revision</button></form></section>
<section><h2>User configuration</h2><button id="read-settings">Read settings</button><textarea id="settings" aria-label="Revisioned user settings"></textarea><button id="write-settings">Replace at this revision</button><pre id="settings-status"></pre></section>
<p>Pause, resume, destination collection, host refusal files and network-tier management are unavailable here.</p>
<script>
const key=new URLSearchParams(location.search).get('k');let cursor='',binding=null;const savedKey='openabstractions-panel-request-v1';
const el=id=>document.getElementById(id);function show(id,x){el(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function call(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Panel-Key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
async function bind(){if(!binding)binding=await call('/binding');return binding}
function recover(){const value=localStorage.getItem(el('saved').value||savedKey);if(!value)throw Error('No saved request. Preserve key, epoch, owner, endpoint and request before submission.');return JSON.parse(value)}
async function inventory(){try{const p=await call('/inventory?cursor='+encodeURIComponent(cursor));if(p.Outcome!=='page'){show('inventory-status',p.Outcome==='gap'?'Cursor expired. Start inventory explicitly.':'Inventory: '+p.Outcome);el('next').disabled=true;return}cursor=p.Next;el('next').disabled=p.Complete;show('inventory-status',p.Complete?'Observed end; restart to see later work.':'More scan pages remain; empty pages can occur.');el('records').replaceChildren();const b=await bind();for(const s of p.Snapshots){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=JSON.stringify(s,null,2);box.append(text);const same=s.Receipt.LogicalOwner===b.history.LogicalOwner;for(const action of ['observe','cancel']){const button=document.createElement('button');button.textContent=action;button.disabled=!same;button.onclick=async()=>{try{show('operation',await call('/action',{action,endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:s.Receipt.Identity}))}catch(e){show('operation',e.message)}};box.append(button)}const result=document.createElement('button');result.textContent='Download completed bytes';result.disabled=!same;result.onclick=()=>{const q=new URLSearchParams({k:key,key:s.Receipt.Identity.Key,epoch:s.Receipt.Identity.HistoryEpoch,owner:b.history.LogicalOwner,endpoint:b.endpoint});location.href='/result?'+q};box.append(result);if(!same){const note=document.createElement('p');note.textContent='Read-only: this inventory owner differs from the selected action provider.';box.append(note)}el('records').append(box)}}catch(e){show('inventory-status',e.message)}}
function savedRequests(selected){el('saved').replaceChildren();for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k.startsWith(savedKey+':'))continue;const o=document.createElement('option');o.value=k;try{o.textContent=JSON.parse(localStorage.getItem(k)).identity.Key}catch{continue}el('saved').append(o)}if(selected)el('saved').value=selected}try{savedRequests()}catch(e){show('operation','Recovery storage unavailable: '+e.message)};
el('restart').onclick=()=>{cursor='';inventory()};el('next').onclick=inventory;
let questionCursor='';const questionText={forbidden:'This panel is not authorized to operate questions; nothing was changed.',unavailable:'The question service could not complete this; no decision is assumed. Retry or list again.',gap:'The question list changed; start the list again.',invalid:'The question service rejected this request as invalid.',unknown:'That question is no longer retained.',conflict:'A different answer is already recorded.'};
function questionStatus(o){return questionText[o]||'Question service outcome: '+o}
async function questionAct(a){try{const r=await call('/questions',a);show('questions-status',r.Outcome==='answered'||r.Outcome==='retired'?(a.action==='answer'?'Answer recorded':'Question retired')+'. List again to refresh.':questionStatus(r.Outcome))}catch(e){show('questions-status',e.message)}}
async function questions(){try{const p=await call('/questions?cursor='+encodeURIComponent(questionCursor));el('questions').replaceChildren();if(p.Outcome!=='page'){show('questions-status',questionStatus(p.Outcome));el('questions-next').disabled=true;return}questionCursor=p.Next;el('questions-next').disabled=p.Complete;show('questions-status',p.Records.length?(p.Complete?'End of current questions.':'More questions remain.'):'No retained questions.');for(const q of p.Records){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=q.Text+'\n'+(q.Option?'Answered: '+q.Option:'Pending');box.append(text);if(!q.Option)for(const option of q.Options){const b=document.createElement('button');b.textContent=option;b.onclick=()=>questionAct({action:'answer',id:q.Id,option});box.append(b)}const retire=document.createElement('button');retire.textContent='Retire';retire.onclick=()=>questionAct({action:'retire',id:q.Id});box.append(retire);el('questions').append(box)}}catch(e){show('questions-status',e.message)}}
el('questions-start').onclick=()=>{questionCursor='';return questions()};el('questions-next').onclick=questions;
let rightsCursor='',rightsRevision='';const rightsText={forbidden:'This panel is not authorized to administer rights; nothing was changed.',unavailable:'The rights service could not complete this; no change is assumed. List again before another edit.',gap:'The policy changed while listing; start the list again.',invalid:'The rights service rejected this rule as invalid.',conflict:'The policy changed since it was listed; nothing was changed. List again and reconcile before another edit.'};
function rightsStatus(o){return rightsText[o]||'Rights service outcome: '+o}
function ruleText(r){return (r.Permit?'permit ':'deny ')+r.Action+' on '+r.Resource+'\nfor '+r.Subject.Account+' running '+r.Subject.Program}
async function rightsEdit(e){if(!rightsRevision){show('rights-status','List policy before editing.');return}try{const r=await call('/rights',{...e,revision:rightsRevision});if(r.Outcome==='applied'){rightsRevision='';show('rights-status',(r.Current?'Rule set: '+ruleText(r.Current):'Rule revoked.')+'\nList again before another edit.')}else show('rights-status',rightsStatus(r.Outcome)+(r.Outcome==='conflict'&&r.Current?'\nCurrent rule: '+ruleText(r.Current):''))}catch(e){show('rights-status',e.message)}}
async function rightsList(){try{const p=await call('/rights?cursor='+encodeURIComponent(rightsCursor));el('rights').replaceChildren();if(p.Outcome!=='page'){rightsRevision='';show('rights-status',rightsStatus(p.Outcome));el('rights-next').disabled=true;return}if(!rightsCursor){el('rights-action').replaceChildren();for(const a of p.Catalog){const o=document.createElement('option');o.value=a;o.textContent=a;el('rights-action').append(o)}}else if(rightsRevision&&p.Revision!==rightsRevision){rightsRevision='';show('rights-status',rightsStatus('gap'));return}rightsRevision=p.Revision;rightsCursor=p.Next;el('rights-next').disabled=p.Complete;show('rights-status','Policy revision '+p.Revision+'. '+(p.Rules.length?(p.Complete?'End of rules.':'More rules remain.'):'No rules on this page; unlisted actions are not granted.'));for(const r of p.Rules){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=ruleText(r);const revoke=document.createElement('button');revoke.textContent='Revoke';revoke.onclick=()=>rightsEdit({edit:'revoke',account:r.Subject.Account,program:r.Subject.Program,action:r.Action,resource:r.Resource});box.append(text,revoke);el('rights').append(box)}}catch(e){rightsRevision='';show('rights-status',e.message)}}
el('rights-start').onclick=()=>{rightsCursor='';return rightsList()};el('rights-next').onclick=rightsList;
el('rights-grant').onsubmit=e=>{e.preventDefault();return rightsEdit({edit:'set',account:el('rights-account').value,program:el('rights-program').value,action:el('rights-action').value,resource:el('rights-resource').value,permit:el('rights-permit').value==='permit'})};
el('status').onclick=async()=>{try{show('runtime',await call('/runtime'))}catch(e){show('runtime',e.message)}};
el('submit').onsubmit=async e=>{e.preventDefault();try{const b=await bind();const a={action:'submit',endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:{Key:el('requestkey').value,HistoryEpoch:b.history.HistoryEpoch},url:el('url').value,digest:el('digest').value,size:Number(el('size').value)};if(!Number.isSafeInteger(a.size)||a.size<0)throw Error('Size must be a nonnegative safe integer');const recordKey=savedKey+':'+JSON.stringify([a.endpoint,a.owner,a.identity.HistoryEpoch,a.identity.Key]);const previous=localStorage.getItem(recordKey);if(previous&&previous!==JSON.stringify(a))throw Error('This key already records different work. Reconcile it; choose a new key only for genuinely new work.');localStorage.setItem(recordKey,JSON.stringify(a));localStorage.setItem(savedKey,JSON.stringify(a));savedRequests(recordKey);show('operation',await call('/action',a))}catch(e){show('operation',e.message+' Retain the saved request; use Reconcile before any new submission.')}};
el('reconcile').onclick=async()=>{try{show('operation',await call('/action',{...recover(),action:'reconcile'}))}catch(e){show('operation',e.message)}};
el('export').onclick=()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(recover(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='operation-recovery.json';a.click();URL.revokeObjectURL(url)}catch(e){show('operation',e.message)}};
el('read-settings').onclick=async()=>{try{el('settings').value=JSON.stringify(await call('/settings'),null,2)}catch(e){show('settings-status',e.message)}};
el('write-settings').onclick=async()=>{try{const r=await call('/settings',JSON.parse(el('settings').value));show('settings-status',r.Outcome==='conflict'?'Settings changed; reread before editing.':r.Outcome);if(r.Outcome==='applied')el('settings').value=JSON.stringify(r.Snapshot,null,2)}catch(e){show('settings-status',e.message)}};
</script>`
