package main

const servicePage = `<!doctype html><meta charset="utf-8"><title>OpenAbstractions services</title>
<style>body{font:16px system-ui;max-width:960px;margin:2rem auto;padding:1rem}input,textarea,button{font:inherit;margin:.3rem;padding:.4rem}textarea{width:95%;height:10rem}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{cursor:pointer}section{border-top:1px solid #aaa;padding:1rem 0}.error{color:#b22}</style>
<h1>Service control panel</h1><p>Work accepted for this panel program only. Other applications keep their own scope. Service absence is reported explicitly.</p>
<button id="status">Check runtime</button><pre id="runtime"></pre>
<section><h2>Accepted work</h2><button id="restart">Start inventory</button><button id="next" disabled>Next page</button><p id="inventory-status"></p><div id="records"></div></section>
<section><h2>Submit verified HTTP download</h2><p>Save the recovery record before submitting. An uncertain reply must be reconciled with the same key and owner.</p>
<form id="submit"><input id="url" type="url" required placeholder="HTTP URL"><input id="digest" required placeholder="sha256:…"><input id="size" type="number" min="0" required placeholder="bytes"><input id="requestkey" required placeholder="unique request key"><button>Save recovery record and submit</button></form>
<select id="saved" aria-label="Saved recovery requests"></select><button id="reconcile">Reconcile saved request</button><button id="export">Export saved recovery record</button><pre id="operation"></pre></section>
<section><h2>User configuration</h2><button id="read-settings">Read settings</button><textarea id="settings" aria-label="Revisioned user settings"></textarea><button id="write-settings">Replace at this revision</button><pre id="settings-status"></pre></section>
<p>Pause, resume, legacy destination collection, host refusal files and network-tier management are unavailable here. The explicit --legacy-local option retains the old embedded-provider controls.</p>
<script>
const key=new URLSearchParams(location.search).get('k');let cursor='',binding=null;const savedKey='openabstractions-panel-request-v1';
const el=id=>document.getElementById(id);function show(id,x){el(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function call(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Panel-Key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
async function bind(){if(!binding)binding=await call('/binding');return binding}
function recover(){const value=localStorage.getItem(el('saved').value||savedKey);if(!value)throw Error('No saved request. Preserve key, epoch, owner, endpoint and request before submission.');return JSON.parse(value)}
async function inventory(){try{const p=await call('/inventory?cursor='+encodeURIComponent(cursor));if(p.Outcome!=='page'){show('inventory-status',p.Outcome==='gap'?'Cursor expired. Start inventory explicitly.':'Inventory: '+p.Outcome);el('next').disabled=true;return}cursor=p.Next;el('next').disabled=p.Complete;show('inventory-status',p.Complete?'Observed end; restart to see later work.':'More scan pages remain; empty pages can occur.');el('records').replaceChildren();const b=await bind();for(const s of p.Snapshots){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=JSON.stringify(s,null,2);box.append(text);const same=s.Receipt.LogicalOwner===b.history.LogicalOwner;for(const action of ['observe','cancel']){const button=document.createElement('button');button.textContent=action;button.disabled=!same;button.onclick=async()=>{try{show('operation',await call('/action',{action,endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:s.Receipt.Identity}))}catch(e){show('operation',e.message)}};box.append(button)}const result=document.createElement('button');result.textContent='Download completed bytes';result.disabled=!same;result.onclick=()=>{const q=new URLSearchParams({k:key,key:s.Receipt.Identity.Key,epoch:s.Receipt.Identity.HistoryEpoch,owner:b.history.LogicalOwner,endpoint:b.endpoint});location.href='/result?'+q};box.append(result);if(!same){const note=document.createElement('p');note.textContent='Read-only: this inventory owner differs from the selected action provider.';box.append(note)}el('records').append(box)}}catch(e){show('inventory-status',e.message)}}
function savedRequests(selected){el('saved').replaceChildren();for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k.startsWith(savedKey+':'))continue;const o=document.createElement('option');o.value=k;try{o.textContent=JSON.parse(localStorage.getItem(k)).identity.Key}catch{continue}el('saved').append(o)}if(selected)el('saved').value=selected}try{savedRequests()}catch(e){show('operation','Recovery storage unavailable: '+e.message)};
el('restart').onclick=()=>{cursor='';inventory()};el('next').onclick=inventory;
el('status').onclick=async()=>{try{show('runtime',await call('/runtime'))}catch(e){show('runtime',e.message)}};
el('submit').onsubmit=async e=>{e.preventDefault();try{const b=await bind();const a={action:'submit',endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:{Key:el('requestkey').value,HistoryEpoch:b.history.HistoryEpoch},url:el('url').value,digest:el('digest').value,size:Number(el('size').value)};if(!Number.isSafeInteger(a.size)||a.size<0)throw Error('Size must be a nonnegative safe integer');const recordKey=savedKey+':'+JSON.stringify([a.endpoint,a.owner,a.identity.HistoryEpoch,a.identity.Key]);const previous=localStorage.getItem(recordKey);if(previous&&previous!==JSON.stringify(a))throw Error('This key already records different work. Reconcile it; choose a new key only for genuinely new work.');localStorage.setItem(recordKey,JSON.stringify(a));localStorage.setItem(savedKey,JSON.stringify(a));savedRequests(recordKey);show('operation',await call('/action',a))}catch(e){show('operation',e.message+' Retain the saved request; use Reconcile before any new submission.')}};
el('reconcile').onclick=async()=>{try{show('operation',await call('/action',{...recover(),action:'reconcile'}))}catch(e){show('operation',e.message)}};
el('export').onclick=()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(recover(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='operation-recovery.json';a.click();URL.revokeObjectURL(url)}catch(e){show('operation',e.message)}};
el('read-settings').onclick=async()=>{try{el('settings').value=JSON.stringify(await call('/settings'),null,2)}catch(e){show('settings-status',e.message)}};
el('write-settings').onclick=async()=>{try{const r=await call('/settings',JSON.parse(el('settings').value));show('settings-status',r.Outcome==='conflict'?'Settings changed; reread before editing.':r.Outcome);if(r.Outcome==='applied')el('settings').value=JSON.stringify(r.Snapshot,null,2)}catch(e){show('settings-status',e.message)}};
</script>`
