package main

const servicePage = `<!doctype html><meta charset="utf-8"><title>OpenAbstractions services</title>
<style>body{font:16px system-ui;max-width:960px;margin:2rem auto;padding:1rem}input,textarea,button{font:inherit;margin:.3rem;padding:.4rem}textarea{width:95%;height:10rem}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{cursor:pointer}section{border-top:1px solid #aaa;padding:1rem 0}.error{color:#b22}.gap{border-left:6px solid #b60;background:#fff4e5;color:#4a2a00;padding:.4rem .6rem;margin:.4rem 0}.record{border-left:6px solid #ccc;padding:.2rem .6rem;margin:.4rem 0}.record p,.gap p{margin:.2rem 0}.hop{list-style:none;margin:.1rem 0}.verified{color:#064;font-weight:600}.verified::before{content:"verified  ";background:#064;color:#fff;border-radius:3px;padding:0 .3rem;margin-right:.4rem;font-size:.8em}.claim{color:#666;font-style:italic}.claim::before{content:"claim  ";background:#ddd;color:#333;border-radius:3px;padding:0 .3rem;margin-right:.4rem;font-size:.8em;font-style:normal}.asserted{color:#8a5a00}.asserted::before{content:"untrusted  ";background:#fc6;color:#000;border-radius:3px;padding:0 .3rem;margin-right:.4rem;font-size:.8em}</style>
<h1>Service control panel</h1><p>Work accepted for this panel program only. Other applications keep their own scope. Service absence is reported explicitly.</p>
<p><a id="credentials-link" href="#">Credentials</a></p>
<button id="status">Check runtime</button><pre id="runtime"></pre>
<section><h2>Accepted work</h2><button id="restart">Start inventory</button><button id="next" disabled>Next page</button><p id="inventory-status"></p><div id="records"></div></section>
<section><h2>Every program's work</h2><p>Work every program in this account submitted. The runtime lists it while this Panel holds the rule abstraction.job/inventory.read, and cancels another program's work under abstraction.job/acceptance.cancel.</p><button id="account-start">List every program's work</button><button id="account-next" disabled>Next page</button><pre id="account-status"></pre><div id="account"></div></section>
<section><h2>Submit verified HTTP download</h2><p>Save the recovery record before submitting. An uncertain reply must be reconciled with the same key and owner.</p>
<form id="submit"><input id="url" type="url" required placeholder="HTTP URL"><input id="digest" required placeholder="sha256:…"><input id="size" type="number" min="0" required placeholder="bytes"><input id="requestkey" required placeholder="unique request key"><button>Save recovery record and submit</button></form>
<select id="saved" aria-label="Saved recovery requests"></select><button id="reconcile">Reconcile saved request</button><button id="export">Export saved recovery record</button><pre id="operation"></pre></section>
<section><h2>Questions</h2><p>Answers and retirements record this person's decision. The question service decides whether this panel may act; retiring tells the application the question is gone, which is neither approval nor refusal.</p><button id="questions-start">List questions</button><button id="questions-next" disabled>Next page</button><pre id="questions-status"></pre><div id="questions"></div></section>
<section><h2>Rights</h2><p>Grants and denies are exact rules for one account, program, action and resource. Every edit applies only at the listed policy revision; the rights service decides whether this panel may administer policy. Resource services still check each call.</p><button id="rights-start">List policy</button><button id="rights-next" disabled>Next page</button><pre id="rights-status"></pre><div id="rights"></div>
<form id="rights-grant"><input id="rights-account" required placeholder="account"><input id="rights-program" required placeholder="absolute program path"><select id="rights-action" aria-label="Catalogue action"></select><input id="rights-resource" required placeholder="resource"><select id="rights-permit" aria-label="Rule"><option value="permit">permit</option><option value="deny">deny</option></select><button>Set at listed revision</button></form>
<form id="rights-allow"><select id="allow-for" aria-label="Bundle"><option value="downloads">Allow downloads for…</option><option value="inference">Allow inference for…</option></select><input id="allow-program" list="allow-programs" required placeholder="absolute program path"><datalist id="allow-programs"></datalist><input id="allow-account" placeholder="account (default: listed rules' account)"><input id="allow-names" placeholder="registries (downloads) or hosts (inference), comma-separated"><input id="allow-credentials" placeholder="credential names, comma-separated"><button>Allow at listed revision</button></form><p>Allow writes each exact rule of the bundle for that program. A system interpreter such as python.exe is one program for every script it runs, so allowing it allows them all.</p></section>
<section><h2>Inference</h2><p>Hosts and each credential's spend, the gateway window's local keys, and the inference audit, through the runtime's inference operator service.</p><a id="inference-link" href="#">Open the inference page</a></section>
<section><h2>Registry</h2><p>Where hosts and providers come from: who declared each host and the profiles it serves, declared provider processes and their readiness, and the hosts remote runtimes report.</p><a id="registry-link" href="#">Open the registry page</a></section>
<section><h2>Logging</h2><p>Records retained by the runtime's logging service, read page by page from the start, or followed live from where reading stopped or from the current end. Each record lists its attestation hops: the writer's own claim is unverified, and a stamp the logging service made itself is verified. A gap is shown as a gap.</p><form id="log-filter"><input id="log-program" placeholder="program"><select id="log-level" aria-label="Lowest level"><option value="">any level</option><option value="-4">DEBUG and above</option><option value="0">INFO and above</option><option value="4">WARN and above</option><option value="8">ERROR and above</option></select><input id="log-since" type="datetime-local" aria-label="From"><input id="log-until" type="datetime-local" aria-label="Until"></form><button id="log-start">Read from the start</button><button id="log-next" disabled>Next page</button><button id="log-follow">Follow live</button><pre id="log-status"></pre><pre id="log-sink"></pre><div id="log-records"></div></section><section><h2>Identity</h2><p>Which runtime this machine selected, how the runtime and its logging service bound this Panel as a caller, and what this platform can prove.</p><button id="identity-check">Check identity</button><pre id="identity-status"></pre><div id="identity"></div></section><section><h2>Explore</h2><p>Calls each capability as this Panel and shows the typed outcome beside the exact rights rule that decides it. Grant or revoke that rule for a program, and the call runs again. A probe marked writes changes state and asks before it runs. The Panel acts only as itself; to act as another program, run a copy of openabstractions named openabstractions-probe under that program's path.</p><form id="explore-subject"><input id="explore-program" aria-label="Program" placeholder="absolute program path"><input id="explore-account" aria-label="Account" placeholder="account"></form><button id="explore-load">Load probes</button><pre id="explore-status"></pre><div id="explore"></div></section><section><h2>User configuration</h2><button id="read-settings">Read settings</button><textarea id="settings" aria-label="Revisioned user settings"></textarea><button id="write-settings">Replace at this revision</button><pre id="settings-status"></pre><p>Follow effective settings from the runtime. Observations leave your editing draft intact. After a conflict, save your draft before reading again.</p><button id="follow-settings">Follow effective settings</button><pre id="settings-observation-status" aria-live="polite"></pre><pre id="effective-settings"></pre></section>
<p>Pause, resume, destination collection, host refusal files and network-tier management are unavailable here.</p>
<script>
const key=new URLSearchParams(location.search).get('k');let cursor='',binding=null;const savedKey='openabstractions-panel-request-v1';
const el=id=>document.getElementById(id);el('inference-link').href='/inference?k='+encodeURIComponent(key);el('registry-link').href='/registry?k='+encodeURIComponent(key);function show(id,x){el(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
el('credentials-link').href='/credentials-page?k='+encodeURIComponent(key);
async function call(path,body,signal){const r=await fetch(path,{signal,method:body?'POST':'GET',headers:{'X-Panel-Key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
async function bind(){if(!binding)binding=await call('/binding');return binding}
function recover(){const value=localStorage.getItem(el('saved').value||savedKey);if(!value)throw Error('No saved request. Preserve key, epoch, owner, endpoint and request before submission.');return JSON.parse(value)}
function jobWaiting(s){return s.Waiting?' (waiting: '+(/^[a-z0-9_.:-]{1,64}$/.test(s.Waiting)?s.Waiting:'unnamed')+')':''}
function jobLabel(s){return (s.Label?s.Label+(s.LabelDerived?' (derived)':''):'Unlabelled operation '+s.Receipt.OperationID)+jobWaiting(s)+' - '+s.State}
async function inventory(){try{const p=await call('/inventory?cursor='+encodeURIComponent(cursor));if(p.Outcome!=='page'){show('inventory-status',p.Outcome==='gap'?'Cursor expired. Start inventory explicitly.':'Inventory: '+p.Outcome);el('next').disabled=true;return}cursor=p.Next;el('next').disabled=p.Complete;show('inventory-status',p.Complete?'Observed end; restart to see later work.':'More scan pages remain; empty pages can occur.');el('records').replaceChildren();const b=await bind();for(const s of p.Snapshots){const box=document.createElement('div');const title=document.createElement('h3');title.textContent=jobLabel(s);const text=document.createElement('pre');text.textContent=JSON.stringify(s,null,2);box.append(title,text);const same=s.Receipt.LogicalOwner===b.history.LogicalOwner;for(const action of ['observe','cancel']){const button=document.createElement('button');button.textContent=action;button.disabled=!same;button.onclick=async()=>{try{show('operation',await call('/action',{action,endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:s.Receipt.Identity}))}catch(e){show('operation',e.message)}};box.append(button)}const result=document.createElement('button');result.textContent='Download completed bytes';result.disabled=!same;result.onclick=()=>{const q=new URLSearchParams({k:key,key:s.Receipt.Identity.Key,epoch:s.Receipt.Identity.HistoryEpoch,owner:b.history.LogicalOwner,endpoint:b.endpoint});location.href='/result?'+q};box.append(result);if(!same){const note=document.createElement('p');note.textContent='Read-only: this inventory owner differs from the selected action provider.';box.append(note)}el('records').append(box)}}catch(e){show('inventory-status',e.message)}}
function savedRequests(selected){el('saved').replaceChildren();for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k.startsWith(savedKey+':'))continue;const o=document.createElement('option');o.value=k;try{o.textContent=JSON.parse(localStorage.getItem(k)).identity.Key}catch{continue}el('saved').append(o)}if(selected)el('saved').value=selected}try{savedRequests()}catch(e){show('operation','Recovery storage unavailable: '+e.message)};
el('restart').onclick=()=>{cursor='';inventory()};el('next').onclick=inventory;
let questionCursor='';const questionText={forbidden:'This panel is not authorized to operate questions; nothing was changed.',unavailable:'The question service could not complete this; no decision is assumed. Retry or list again.',gap:'The question list changed; start the list again.',invalid:'The question service rejected this request as invalid.',unknown:'That question is no longer retained.',conflict:'A different answer is already recorded.'};
function questionStatus(o){return questionText[o]||'Question service outcome: '+o}
function questionRule(r){if(!r.rule)return '';const what=(r.rule.Permit?'permit ':'deny ')+r.rule.Action+' on '+r.rule.Resource+' for '+r.rule.Subject.Program;if(r.edit&&r.edit.Outcome==='applied')return '\nRule written: '+what+' (asked at first use).';return '\nThe rule was not written ('+(r.edit?r.edit.Outcome:r.ruleOutcome||'no decision')+'): '+what+'. List the questions and choose Retry rule.'}
const ruleStateText={written:'Rule written.',not_written:'Answered, rule not written.'};
async function questionAct(a){try{const r=await call('/questions',a);show('questions-status',r.Outcome==='answered'||r.Outcome==='retired'?(a.action==='answer'?'Answer recorded':'Question retired')+'.'+questionRule(r)+' List again to refresh.':questionStatus(r.Outcome))}catch(e){show('questions-status',e.message)}}
async function questions(){try{const p=await call('/questions?cursor='+encodeURIComponent(questionCursor));el('questions').replaceChildren();if(p.Outcome!=='page'){show('questions-status',questionStatus(p.Outcome));el('questions-next').disabled=true;return}questionCursor=p.Next;el('questions-next').disabled=p.Complete;show('questions-status',p.Records.length?(p.Complete?'End of current questions.':'More questions remain.'):'No retained questions.');for(const q of p.Records){const box=document.createElement('div');const text=document.createElement('pre');const state=(p.ruleStates||{})[q.ID];text.textContent=q.Text+'\n'+(q.Option?'Answered: '+q.Option:'Pending')+(state?'\n'+(ruleStateText[state]||'Rule state: '+state):'');box.append(text);if(!q.Option)for(const option of q.Options){const b=document.createElement('button');b.textContent=option;b.onclick=()=>questionAct({action:'answer',id:q.ID,option});box.append(b)}if(state==='not_written'){const retry=document.createElement('button');retry.textContent='Retry rule';retry.onclick=()=>questionAct({action:'answer',id:q.ID,option:q.Option});box.append(retry)}const retire=document.createElement('button');retire.textContent='Retire';retire.onclick=()=>questionAct({action:'retire',id:q.ID});box.append(retire);el('questions').append(box)}}catch(e){show('questions-status',e.message)}}
el('questions-start').onclick=()=>{questionCursor='';return questions()};el('questions-next').onclick=questions;
let rightsCursor='',rightsRevision='';const rightsText={forbidden:'This panel is not authorized to administer rights; nothing was changed.',unavailable:'The rights service could not complete this; no change is assumed. List again before another edit.',gap:'The policy changed while listing; start the list again.',invalid:'The rights service rejected this rule as invalid.',conflict:'The policy changed since it was listed; nothing was changed. List again and reconcile before another edit.'};
function rightsStatus(o){return rightsText[o]||'Rights service outcome: '+o}
function ruleText(r){return (r.Permit?'permit ':'deny ')+r.Action+' on '+r.Resource+'\nfor '+r.Subject.Account+' running '+r.Subject.Program}
async function rightsEdit(e){if(!rightsRevision){show('rights-status','List policy before editing.');return}try{const r=await call('/rights',{...e,revision:rightsRevision});if(r.Outcome==='applied'){rightsRevision='';show('rights-status',(r.Current?'Rule set: '+ruleText(r.Current):'Rule revoked.')+'\nList again before another edit.')}else show('rights-status',rightsStatus(r.Outcome)+(r.Outcome==='conflict'&&r.Current?'\nCurrent rule: '+ruleText(r.Current):''))}catch(e){show('rights-status',e.message)}}
async function rightsList(){try{const p=await call('/rights?cursor='+encodeURIComponent(rightsCursor));el('rights').replaceChildren();if(p.Outcome!=='page'){rightsRevision='';show('rights-status',rightsStatus(p.Outcome));el('rights-next').disabled=true;return}if(!rightsCursor){el('rights-action').replaceChildren();for(const a of p.Catalog){const o=document.createElement('option');o.value=a;o.textContent=a;el('rights-action').append(o)}}else if(rightsRevision&&p.Revision!==rightsRevision){rightsRevision='';show('rights-status',rightsStatus('gap'));return}rightsRevision=p.Revision;rightsCursor=p.Next;allowPrograms(p.Rules.map(r=>r.Subject));el('rights-next').disabled=p.Complete;show('rights-status','Policy revision '+p.Revision+'. '+(p.Rules.length?(p.Complete?'End of rules.':'More rules remain.'):'No rules on this page; unlisted actions are not granted.'));for(const r of p.Rules){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=ruleText(r);const revoke=document.createElement('button');revoke.textContent='Revoke';revoke.onclick=()=>rightsEdit({edit:'revoke',account:r.Subject.Account,program:r.Subject.Program,action:r.Action,resource:r.Resource});box.append(text,revoke);el('rights').append(box)}}catch(e){rightsRevision='';show('rights-status',e.message)}}
let accountCursor='';const accountText={forbidden:'This Panel holds no rule for this; nothing was listed or changed.',unavailable:'The runtime could not obtain a decision; nothing was listed or changed. Try again.',gap:'The work changed while listing; start the list again.',invalid:'The job service rejected this request.',unknown:'No operation has this id.'};
async function accountCancel(id){try{const r=await call('/account-work',{operation:id});show('account-status',id+': '+(r.Outcome==='requested'?'cancellation requested; the program that submitted it sees the end.':r.Outcome==='already_terminal'?'already ended.':(accountText[r.Outcome]||'Job service outcome: '+r.Outcome)))}catch(e){show('account-status',e.message)}}
async function accountList(){try{const p=await call('/account-work?cursor='+encodeURIComponent(accountCursor));el('account').replaceChildren();if(p.Outcome!=='page'){show('account-status',accountText[p.Outcome]||'Job service outcome: '+p.Outcome);el('account-next').disabled=true;return}accountCursor=p.Next;el('account-next').disabled=p.Complete;show('account-status',p.Snapshots.length?(p.Complete?'End of work.':'More work remains.'):'No work on this page.');for(const s of p.Snapshots){const box=document.createElement('div');const text=document.createElement('pre');text.textContent=s.Receipt.OperationID+' - '+s.State+(s.Label?' - '+s.Label:'');const cancel=document.createElement('button');cancel.textContent='Cancel';cancel.onclick=()=>accountCancel(s.Receipt.OperationID);box.append(text,cancel);el('account').append(box)}}catch(e){show('account-status',e.message)}}
el('account-start').onclick=()=>{accountCursor='';return accountList()};el('account-next').onclick=accountList;
el('rights-start').onclick=()=>{rightsCursor='';return rightsList()};el('rights-next').onclick=rightsList;
const allowSeen=new Set();let allowAccount='';
function allowPrograms(subjects){for(const s of subjects){if(!allowAccount)allowAccount=s.Account;if(allowSeen.has(s.Program))continue;allowSeen.add(s.Program);const o=document.createElement('option');o.value=s.Program;el('allow-programs').append(o)}}
function allowList(v){return v.split(',').map(x=>x.trim()).filter(x=>x)}
async function rightsAllow(){if(!rightsRevision){show('rights-status','List policy before allowing.');return}const bundle=el('allow-for').value,names=allowList(el('allow-names').value);const body={for:bundle,revision:rightsRevision,account:el('allow-account').value||allowAccount,program:el('allow-program').value,registries:bundle==='downloads'?names:[],hosts:bundle==='inference'?names:[],credentials:allowList(el('allow-credentials').value)};try{const r=await call('/rights/allow',body);rightsRevision='';const landed=r.landed.map(x=>'permit '+x.action+' on '+x.resource).join('\n');show('rights-status',r.outcome==='applied'?'Allowed '+bundle+' for '+body.program+':\n'+landed+'\nList again before another edit.':(rightsStatus(r.outcome)+'\nStopped at '+r.stopped.action+' on '+r.stopped.resource+'; '+r.landed.length+' of '+r.rules.length+' rules landed'+(landed?':\n'+landed:'.')))}catch(e){rightsRevision='';show('rights-status',e.message)}}
el('rights-allow').onsubmit=e=>{e.preventDefault();return rightsAllow()};
el('rights-grant').onsubmit=e=>{e.preventDefault();return rightsEdit({edit:'set',account:el('rights-account').value,program:el('rights-program').value,action:el('rights-action').value,resource:el('rights-resource').value,permit:el('rights-permit').value==='permit'})};
el('status').onclick=async()=>{try{show('runtime',await call('/runtime'))}catch(e){show('runtime',e.message)}};
el('submit').onsubmit=async e=>{e.preventDefault();try{const b=await bind();const a={action:'submit',endpoint:b.endpoint,owner:b.history.LogicalOwner,identity:{Key:el('requestkey').value,HistoryEpoch:b.history.HistoryEpoch},url:el('url').value,digest:el('digest').value,size:Number(el('size').value)};if(!Number.isSafeInteger(a.size)||a.size<0)throw Error('Size must be a nonnegative safe integer');const recordKey=savedKey+':'+JSON.stringify([a.endpoint,a.owner,a.identity.HistoryEpoch,a.identity.Key]);const previous=localStorage.getItem(recordKey);if(previous&&previous!==JSON.stringify(a))throw Error('This key already records different work. Reconcile it; choose a new key only for genuinely new work.');localStorage.setItem(recordKey,JSON.stringify(a));localStorage.setItem(savedKey,JSON.stringify(a));savedRequests(recordKey);show('operation',await call('/action',a))}catch(e){show('operation',e.message+' Retain the saved request; use Reconcile before any new submission.')}};
el('reconcile').onclick=async()=>{try{show('operation',await call('/action',{...recover(),action:'reconcile'}))}catch(e){show('operation',e.message)}};
el('export').onclick=()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(recover(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='operation-recovery.json';a.click();URL.revokeObjectURL(url)}catch(e){show('operation',e.message)}};
el('read-settings').onclick=async()=>{try{el('settings').value=JSON.stringify(await call('/settings'),null,2)}catch(e){show('settings-status',e.message)}};
el('write-settings').onclick=async()=>{try{const r=await call('/settings',JSON.parse(el('settings').value));show('settings-status',r.Outcome==='conflict'?'Settings changed. Your draft is preserved; save it before reading and reconciling the current revision.':r.Outcome);if(r.Outcome==='applied')el('settings').value=JSON.stringify(r.Snapshot,null,2)}catch(e){show('settings-status',e.message)}};
let settingsFollow=null;
function stopSettingsFollow(){if(settingsFollow)settingsFollow.abort();settingsFollow=null;el('follow-settings').textContent='Follow effective settings'}
el('follow-settings').onclick=async()=>{if(settingsFollow){stopSettingsFollow();show('settings-observation-status','Following stopped.');return}const run=new AbortController();settingsFollow=run;el('follow-settings').textContent='Stop following';let cursor='';try{while(settingsFollow===run){const r=await call('/settings/observe?'+new URLSearchParams({cursor}),undefined,run.signal);if(settingsFollow!==run)return;if(r.Outcome==='snapshot'){cursor=r.Cursor;show('effective-settings',r.Snapshot);show('settings-observation-status','Effective settings observed. Your editing draft is unchanged.')}else if(r.Outcome==='unchanged'){cursor=r.Cursor}else{show('settings-observation-status',r.Outcome==='gap'?'Observation continuity was lost. Start following again to read current settings.':'Configuration observation: '+r.Outcome);break}}}catch(e){if(settingsFollow===run)show('settings-observation-status',e.message)}finally{if(settingsFollow===run)stopSettingsFollow()}};
let logCursor=null,logFollowing=false;const logKept=1000;
const logOutcomes={gap:'History gap: the cursor no longer names retained history, because the logging service restarted or its history was replaced. Records in between may be missing. Read from the start to continue.',unavailable:'The logging service has no readable history right now.',unsupported:'The logging service does not offer live observation.',invalid_request:'The logging service refused the request as invalid.',record_too_large:'A retained record is larger than one page and cannot be shown.',corrupt:'The retained history is corrupt at this position.'};
function isoOrEmpty(v){if(!v)return '';const d=new Date(v);return isNaN(d.getTime())?'':d.toISOString()}
function logQuery(extra){return '/logging?'+new URLSearchParams({cursor:logCursor||'',program:el('log-program').value,level:el('log-level').value,since:isoOrEmpty(el('log-since').value),until:isoOrEmpty(el('log-until').value),...extra})}
const standingText={established:'verified by the logging service',vouched:'vouched for through a trusted path',asserted:'asserts verification nothing the Panel trusts stands behind'};
function hopText(h){const who=[h.program&&'program '+h.program,h.exe&&'executable '+h.exe,h.user&&'account '+h.user,h.uid>=0&&'uid '+h.uid,h.pid>=0&&'pid '+h.pid,h.host&&'host '+h.host].filter(Boolean).join(', ');const standing=standingText[h.standing]||(h.by==='unclaimed'?'the writer sent no claim':'the writer\'s own claim, unverified');return 'hop '+h.hop+', '+h.role+' ('+h.by+'): '+standing+(who?'. '+who:'')}
function hopClass(h){return 'hop '+(h.standing==='established'||h.standing==='vouched'?'verified':h.standing==='asserted'?'asserted':'claim')}
function logEntry(r){const box=document.createElement('div');const t=document.createElement('p');if(r.kind==='sink_gap'){box.className='gap';t.textContent='Sink loss: '+r.dropped+' records from '+(r.program||'a writer with no program claim')+' were dropped between '+r.since+' and '+r.until+' while its logging service was unreachable.'}else{box.className='record';t.textContent=r.time+' '+r.levelName+' '+(r.program||'(no program claim)')+': '+r.message+(r.job?' [job '+r.job+']':'')+(r.attrs?' '+JSON.stringify(r.attrs):'')}box.append(t);const hops=document.createElement('ul');for(const h of r.hops){const li=document.createElement('li');li.className=hopClass(h);li.textContent=hopText(h);hops.append(li)}box.append(hops);if(r.disputed){const d=document.createElement('p');d.className='error';d.textContent='Disputed: the writer\'s claim contradicts the stamp about the writer.';box.append(d)}return box}
function sinkText(s){if(!s)return '';if(!s.adopted)return 'This Panel\'s own logging: '+(s.bindError?'not bound. '+s.bindError:'not bound yet; it binds when the Panel first logs an action or checks identity.');return 'This Panel\'s own logging: '+s.state+'. '+s.accepted+' accepted, '+s.written+' written, '+s.queued+' queued, '+s.dropped+' dropped, '+s.failed+' failed, '+s.abandoned+' abandoned'+(s.lastError?'. Last error: '+s.lastError:'')+(s.transition?'. Last transition: '+s.transition:'')}
function logStop(){logFollowing=false;el('log-follow').textContent='Follow live'}
function logPage(v,replace){show('log-sink',sinkText(v.sink));const list=el('log-records');if(replace)list.replaceChildren();if(v.outcome!=='page'){logStop();el('log-next').disabled=true;if(v.outcome==='gap'){logCursor=null;const g=document.createElement('div');g.className='gap';g.textContent=logOutcomes.gap;list.append(g)}show('log-status',logOutcomes[v.outcome]||'Logging service outcome: '+v.outcome);return false}logCursor=v.next;for(const r of v.records)list.append(logEntry(r));if(list.children.length>logKept)list.replaceChildren(...[...list.children].slice(-logKept));el('log-next').disabled=v.atEnd||v.mode==='follow';show('log-status',(v.mode==='follow'?'Following live. ':'')+(v.atEnd?'At the current end of history.':'More history remains.')+(v.hidden?' '+v.hidden+' records on this page hidden by the filter.':''));return true}
async function logRead(){try{logPage(await call(logQuery({})),true)}catch(e){logStop();show('log-status',e.message)}}
el('log-start').onclick=()=>{logStop();logCursor=null;return logRead()};el('log-next').onclick=logRead;
el('log-follow').onclick=async()=>{if(logFollowing){logStop();return}logFollowing=true;el('log-follow').textContent='Stop following';while(logFollowing){try{const v=await call(logQuery({cursor:logCursor||'end',follow:'1',wait:'10000'}));if(!logFollowing||!logPage(v,false))break}catch(e){logStop();show('log-status',e.message);break}}};
function para(parent,text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;parent.append(p);return p}
function heading(parent,text){const h=document.createElement('h3');h.textContent=text;parent.append(h)}
function renderIdentity(v){const out=el('identity');out.replaceChildren();const s=v.selection;
heading(out,'This machine\'s runtime');para(out,'Installed runtime selection: '+s.status+(s.status==='TRUSTED'?'. Program '+s.program+', account '+s.account+', endpoint '+s.endpoint+'.':s.detail?'. '+s.detail:''),s.status==='TRUSTED'?'verified':'error');
if(v.explicit)para(out,'This Panel was started against another runtime at '+v.explicit.endpoint+', which must run '+v.explicit.program+' as account '+v.explicit.account+'.');
for(const d of v.declarations)para(out,'Platform declaration for '+d.name+': '+d.status+'.');
heading(out,'How the runtime bound this Panel');const r=v.runtime;
if(r.outcome==='observed'){para(out,'Account '+r.account+', program '+r.program+', pid '+r.pid+', established by '+r.mechanism+' over '+r.transport+'.','verified');for(const a of r.attributes)para(out,a.attribute+': proven '+a.proof+'; the ceiling on this transport is '+a.ceiling+'.')}else if(r.outcome)para(out,'The runtime answered '+r.outcome+' and showed no identity.','error');else para(out,(r.absent?'The runtime is absent: ':'The runtime refused this Panel: ')+r.error,'error');
for(const c of v.capabilities)para(out,c.name+' ('+c.contract+'): '+c.label+' for this Panel.',c.status==='resolved'?'':c.status==='forbidden'?'error':'');
if(v.capabilityError)para(out,'Resolution check stopped: '+v.capabilityError,'error');
heading(out,'How the logging service bound this Panel');const L=v.logging;
if(L.outcome==='found'){if(L.claim)para(out,'The Panel wrote a record claiming to be '+L.claim.program+'.','claim');if(L.stamp)para(out,'The logging service stamped it: executable '+L.stamp.exe+', account '+(L.stamp.user||L.stamp.uid)+', pid '+L.stamp.pid+' ('+L.stamp.by+', '+(standingText[L.stamp.standing]||L.stamp.standing)+').',L.stamp.standing==='established'?'verified':'asserted');if(L.agreesWithRuntime===true)para(out,'The logging service and the runtime bound the same program, account and process.');if(L.agreesWithRuntime===false)para(out,'The logging service and the runtime disagree about this Panel.','error')}
else para(out,L.absent?'The runtime is absent: '+L.error:'The logging service did not show its view: '+(L.error||L.outcome),'error');
heading(out,'What this platform can prove');const c=v.ceiling;para(out,'Over '+c.transport+' on '+c.platform+' the best proof is user '+c.best.user+', process '+c.best.process+', path '+c.best.path+', package '+c.best.package+', code '+c.best.code+'. '+(c.bindable?'A binding pins the caller\'s process.':'No binding pins the caller\'s process.'));
const limits=document.createElement('ul');for(const l of v.limits){const li=document.createElement('li');li.textContent=l;limits.append(li)}out.append(limits)}
el('identity-check').onclick=async()=>{show('identity-status','Checking identity...');try{const v=await call('/identity');renderIdentity(v);show('identity-status','Checked at '+v.checkedAt+'.')}catch(e){el('identity').replaceChildren();show('identity-status',e.message)}};
let exploreSelf=null;
function exploreQuery(p,arg){const q={capability:p.capability,operation:p.operation,program:el('explore-program').value,account:el('explore-account').value};if(arg)q.argument=arg;if(p.writes)q.confirm='write';return '/explore?'+new URLSearchParams(q)}
function ruleView(r){if(!r)return 'No rights rule decides this call in a runtime that enforces one.';const who=r.subject.account+' running '+r.subject.program;if(r.outcome==='found'||r.outcome==='expired')return 'Rule for '+who+': '+(r.permit?'permit ':'deny ')+r.action+' on '+r.resource+(r.outcome==='expired'?' (expired, decides nothing)':'')+', set by '+(r.setBy?r.setBy.program:'?')+' at '+r.setAt+(r.why?' because '+r.why:'')+'. Policy revision '+r.revision+'.';if(r.outcome==='unknown')return 'No exact rule for '+who+': '+r.action+' on '+r.resource+' is not granted. Policy revision '+r.revision+'.';if(r.outcome==='forbidden')return 'The rights service did not show the rule: this Panel is not a rights operator.';return 'The rule could not be read: '+r.outcome+(r.error?' ('+r.error+')':'')}
function resultView(v){return v.capability+' '+v.operation+' ('+v.contract+') as '+v.subject.program+': '+v.outcome+(v.detail?'. '+v.detail:'')+(v.summary?' '+JSON.stringify(v.summary):'')}
async function exploreRun(p,box){const arg=box.argument?box.argument.value:'';if(p.argument&&!arg){show('explore-status','Name '+p.argument+' for '+p.capability+' '+p.operation+'.');return}if(p.writes&&!confirm(p.capability+' '+p.operation+': '+(p.note||'writes')+'. Call it?')){show('explore-status',p.capability+' '+p.operation+' was not called.');return}try{const v=await call(exploreQuery(p,arg));box.result.textContent=resultView(v.result);box.result.className=v.result.resolution||v.result.outcome==='error'?'error':'';box.rule.textContent=ruleView(v.rule);box.lastRule=v.result.rule;box.grant.disabled=box.revoke.disabled=!v.result.rule}catch(e){box.result.textContent=e.message;box.result.className='error'}}
async function exploreEdit(p,box,edit,permit){if(!box.lastRule){show('explore-status','Call the probe first; its rule names the action and resource.');return}try{const page=await call('/rights?cursor=');if(page.Outcome!=='page'){show('explore-status',rightsStatus(page.Outcome));return}const r=await call('/rights',{edit,revision:page.Revision,account:el('explore-account').value,program:el('explore-program').value,action:box.lastRule.action,resource:box.lastRule.resource,...(edit==='set'?{permit}:{})});show('explore-status',r.Outcome==='applied'?(edit==='set'?(permit?'Granted':'Denied'):'Revoked')+' '+box.lastRule.action+' on '+box.lastRule.resource+' at revision '+page.Revision+'; calling again.':rightsStatus(r.Outcome));if(r.Outcome==='applied')await exploreRun(p,box)}catch(e){show('explore-status',e.message)}}
el('explore-load').onclick=async()=>{try{const v=await call('/explore');exploreSelf=v.self;if(!el('explore-program').value)el('explore-program').value=v.self.program;if(!el('explore-account').value)el('explore-account').value=v.self.account;const list=el('explore');list.replaceChildren();for(const p of v.probes){const box=document.createElement('div');box.className='record';const title=document.createElement('h3');title.textContent=p.capability+' '+p.operation+(p.writes?' (writes)':'');const contract=document.createElement('p');contract.textContent=p.contract+(p.rule?'; decided by '+p.rule.action+' on '+p.rule.resource:'')+(p.note?'. '+p.note:'');box.append(title,contract);if(p.argument){box.argument=document.createElement('input');box.argument.placeholder=p.argument;box.append(box.argument)}const run=document.createElement('button');run.textContent='Call';run.onclick=()=>exploreRun(p,box);box.grant=document.createElement('button');box.grant.textContent='Grant';box.grant.disabled=true;box.grant.onclick=()=>exploreEdit(p,box,'set',true);box.revoke=document.createElement('button');box.revoke.textContent='Revoke';box.revoke.disabled=true;box.revoke.onclick=()=>exploreEdit(p,box,'revoke',false);box.result=document.createElement('pre');box.rule=document.createElement('pre');box.append(run,box.grant,box.revoke,box.result,box.rule);list.append(box)}show('explore-status','Probes act as '+v.self.program+'. Rules name the program above.')}catch(e){show('explore-status',e.message)}};
</script>`
