#!/bin/sh
# Regenerates the Contents block in VISION.md from the entries themselves.
# VISION.md is the only input and the only output. Run it after adding entries.
# Set VISION_FILE to point it at a fixture instead.
set -eu
cd "$(dirname "$0")/.."

src=${VISION_FILE:-VISION.md}
[ -f "$src" ] || { echo "no such file: $src" >&2; exit 1; }
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

prose() { awk '/^<!-- contents:begin/ { b = 1 } !b && NF { print } /^<!-- contents:end/ { b = 0 }' "$1"; }

nb=$(grep -c '^<!-- contents:begin' "$src" || true)
ne=$(grep -c '^<!-- contents:end' "$src" || true)
[ "$nb" -le 1 ] && [ "$ne" -le 1 ] && [ "$nb" = "$ne" ] ||
  { echo "refusing to write: $nb contents:begin markers and $ne contents:end" >&2; exit 1; }

awk '
  /^<!-- contents:begin/ { inblock = 1; next }
  /^<!-- contents:end/   { inblock = 0; next }
  inblock { next }
  /^## / { if (lead != "") flush(); section = substr($0, 4); next }
  /^- (\*\*|~~)/ { if (lead != "") flush(); lead = $0; line = NR; next }
  lead != "" && lead ~ /\*\*/ && lead !~ /\*\*[^*]*\*\*/ { lead = lead " " $0; next }
  lead != "" { flush() }
  END { if (lead != "") flush() }
  function flush(   t, d, dead, st) {
    t = lead
    dead = (t ~ /~~/) ? "x" : ""
    sub(/^- +/, "", t); gsub(/~~/, "", t)
    sub(/^\*\*/, "", t); sub(/\*\*.*/, "", t)
    gsub(/`|\*/, "", t); gsub(/\t/, " ", t); gsub(/  +/, " ", t)
    d = ""
    if (t ~ /^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/) { d = substr(t, 1, 10); t = substr(t, 12) }
    sub(/^[ .,-]+/, "", t); gsub(/·/, "", t); sub(/^ +/, "", t); sub(/[ .]+$/, "", t)
    if (length(t) > 96) t = substr(t, 1, 93) "..."
    st = section; sub(/ — .*/, "", st); sub(/ - .*/, "", st); sub(/,.*/, "", st)
    printf "%s\t%s\t%s\t%s\t%s\n", st, d, line, t, dead
    lead = ""
  }
' "$src" > "$work/leads-raw"

build_block() {
  leads=$1
  total=$(wc -l < "$leads" | tr -d ' ')
  dead=$(awk -F'\t' '$5 == "x"' "$leads" | wc -l | tr -d ' ')
  echo '<!-- contents:begin - generated by scripts/vision-index.sh, do not hand-edit -->'
  echo
  echo '## Contents'
  echo
  echo 'This is a timeline, newest day first. Nobody reads the file front to back'
  echo 'and nobody should - it is a ledger, written often, searched sometimes, read'
  echo 'whole never. **What is true right now is one screen at the top of'
  echo '`PROGRESS.md`.** Come here to find what was already decided about one thing.'
  echo
  printf '**%s entries, of which %s are struck.** A struck entry is a decision that\n' "$total" "$dead"
  echo 'died. It keeps its place in the timeline and is marked **DEAD** - a decision'
  echo 'moved somewhere else stops being visible where anyone would try to revive it,'
  echo 'which is the whole reason a strike is a strike and not a deletion. New strikes'
  echo 'happen where the decision was taken; the *Struck out* section is older history'
  echo 'and no longer grows. Each day heading carries how many entries it holds.'
  echo
  echo 'Line anchors are line numbers in this file as it stands. Regenerate after'
  echo 'adding entries: `sh scripts/vision-index.sh`.'
  sort -t"$(printf '\t')" -k2,2r -s "$leads" | awk -F'\t' '
    { n++; day[n] = $2; sec[n] = $1; ln[n] = $3; title[n] = $4; dd[n] = $5; cnt[$2]++ }
    END {
      prev = "\001"
      for (i = 1; i <= n; i++) {
        if (day[i] != prev) {
          prev = day[i]
          label = (prev == "" ? "Undated" : prev)
          printf "\n### %s (%d %s)\n\n", label, cnt[prev], (cnt[prev] == 1 ? "entry" : "entries")
        }
        printf "- L%s %s`%s` %s\n", ln[i], (dd[i] == "x" ? "**DEAD** " : ""), sec[i], title[i]
      }
    }
  '
  echo
  echo '<!-- contents:end -->'
}

if [ "$nb" = 1 ]; then
  b=$(grep -n '^<!-- contents:begin' "$src" | cut -d: -f1)
  e=$(grep -n '^<!-- contents:end' "$src" | cut -d: -f1)
  [ "$e" -gt "$b" ] || { echo "refusing to write: contents:end precedes contents:begin" >&2; exit 1; }
  oldlen=$((e - b + 1))
  mode=after
  cutoff=$e
else
  at=$(grep -n '^\(- \(\*\*\|~~\)\|## \)' "$src" | head -1 | cut -d: -f1)
  [ -n "$at" ] || at=$(($(wc -l < "$src") + 1))
  oldlen=0
  mode=all
  cutoff=$((at - 1))
fi

build_block "$work/leads-raw" > "$work/block-raw"
newlen=$(wc -l < "$work/block-raw" | tr -d ' ')
if [ "$mode" = all ]; then
  delta=$((newlen + 1))
else
  delta=$((newlen - oldlen))
fi

awk -F'\t' -v OFS='\t' -v delta="$delta" -v cutoff="$cutoff" -v mode="$mode" '
  { if (mode == "all" || $3 + 0 > cutoff) $3 = $3 + delta; print }
' "$work/leads-raw" > "$work/leads-final"

build_block "$work/leads-final" > "$work/block"

if [ "$nb" = 1 ]; then
  head -n $((b - 1)) "$src" > "$work/out"
  cat "$work/block" >> "$work/out"
  tail -n +$((e + 1)) "$src" >> "$work/out"
else
  head -n $((at - 1)) "$src" > "$work/out"
  cat "$work/block" >> "$work/out"
  echo >> "$work/out"
  tail -n +"$at" "$src" >> "$work/out"
fi

was=$(grep -c '^- \(\*\*\|~~\)' "$src" || true)
now=$(grep -c '^- \(\*\*\|~~\)' "$work/out" || true)
[ "$now" -ge "$was" ] || { echo "refusing to write: $was entries in, $now out" >&2; exit 1; }

prose "$src" > "$work/before"
prose "$work/out" > "$work/after"
cmp -s "$work/before" "$work/after" ||
  { echo "refusing to write: prose outside the contents block would change" >&2; exit 1; }

cp "$work/out" "$src"
total=$(wc -l < "$work/leads-final" | tr -d ' ')
dead=$(awk -F'\t' '$5 == "x"' "$work/leads-final" | wc -l | tr -d ' ')
echo "$total entries indexed, $dead struck"
